lib/BenchIteration.php, lib/BenchRunner.php, lib/Console/Command/BenchRunCommand.php, lib/ReportGenerator/BaseTabularReportGenerator.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php, tests/Functional/ReportGenerator/XmlReportGeneratorTest.php
Added support for reporting memory:
````php
php ./bin/phpbench run tests/assets/functional --report='{"name": "console_table", "memory": true, "memory_inc": true}'
Running benchmarking suite
BenchmarkCase
...
Generating reports...
>> console_table >>
BenchmarkCase#benchParameterized(): Parameterized bench mark
+------+--------+----------+------------+--------+-------------+------------+-----------------+
| iter | length | strategy | time       | memory | memory_diff | memory_inc | memory_diff_inc |
+------+--------+----------+------------+--------+-------------+------------+-----------------+
| 1    | 1      | left     | 0.00001287 | 144    | +144        | 2,795,304  | +5,688          |
| 1    | 2      | left     | 0.00001192 | 288    | +144        | 2,796,656  | +1,352          |
| 1 …
```
=> Added memory reporting

README.md, bin/phpbench.php, lib/Benchmark/Configuration.php, lib/Configuration.php, lib/Console/Application.php, lib/Console/Command/BaseCommand.php, lib/Console/Command/ReportCommand.php, lib/Console/Command/RunCommand.php, lib/ReportGenerator.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, lib/ReportGenerator/OutputAwareReport.php, lib/ReportGenerator/XmlTableReportGenerator.php, tests/Functional/Bin/BinTest.php, tests/Functional/Bin/env/config_dist/.phpbench.dist, tests/Functional/Bin/env/config_valid/.phpbench, tests/Functional/Bin/env/config_valid/.phpbench.dist, tests/Functional/Console/Command/RunCommandTest.php, tests/Functional/ReportGenerator/BaseReportGeneratorCase.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php, tests/Functional/ReportGenerator/ConsoleReportGeneratorTest.php, tests/Functional/ReportGenerator/XmlReportGeneratorTest.php, tests/Unit/Benchmark/CollectionBuilderTest.php, tests/Unit/Benchmark/findertest/AbstractBench.php, tests/Unit/ConfigurationTest.php
The configuration class allows hte user to define default settings in the `.phpbench` or `.phpbench.dist` file , or a configuration file specified with the `--config` option.
The configuration file is a plain PHP file and must instantiate the `Configuration` class and bootstrap any autoloading required. (if no configuration is present `vendor/autoload.php` will be used).
It is possible for the user to add their own `ReportGenerator` instances, and eventually `ProgressLogger` instances if required.
=> Introducing Configuration class

README.md, lib/Benchmark/Runner.php, tests/Unit/Benchmark/RunnerTest.php
If `setUp` and or `tearDown` are present in the benchmarking class, then they will be executed before and after the benchmark class.
=> Setup teardown

lib/Benchmark/Runner.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php
Show time either as a fraction of a second (`0.000032`) or as an integer representing microseconds (`32`)
=> Allow choice of showing in time in fraction of second in in microseconds

.travis.yml, README.md, lib/Benchmark/Parser.php, lib/Benchmark/Runner.php, lib/Benchmark/Subject.php, lib/Benchmark/SubjectBuilder.php, lib/Console/Command/RunCommand.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, lib/Result/Dumper/XmlDumper.php, lib/Result/Loader/XmlLoader.php, lib/Result/SuiteResult.php, tests/Functional/Bin/BinTest.php, tests/Functional/Console/Command/RunCommandTest.php, tests/Functional/ReportGenerator/BaseReportGeneratorCase.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php, tests/Functional/ReportGenerator/report.xml, tests/Functional/benchmarks/ArrayKeysCase.php, tests/Functional/benchmarks/IsolatedCase.php, tests/Functional/benchmarks/IsolatedParametersCase.php, tests/Unit/Benchmark/ParserTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/ReportGenerator/ConsoleTableReportGeneratorTest.php, tests/Unit/Result/Dumper/XmlDumperTest.php, tests/Unit/Result/Loader/XmlLoaderTest.php, tests/phpbench
Support for running benchmarks in separate processes.
Allows both running each individual iteration in isolation in addition to running sets of parameterized iterations in isolation.
Process isolation can be triggered via annotations or globally with the `--processisolation` option.
In addition this PR adds options for globally specifying parameters and the number of iterations to run for each test.
=> Process Isolation

.travis.yml, CHANGELOG.md, README.md, composer.json, examples/CostOfReflectionBench.php, examples/phpbench, lib/Benchmark/Parser.php, lib/Benchmark/Runner.php, lib/Benchmark/Subject.php, lib/Benchmark/SubjectBuilder.php, lib/Console/Command/RunCommand.php, lib/PhpBench.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, lib/Result/Dumper/XmlDumper.php, lib/Result/Loader/XmlLoader.php, lib/Result/SubjectResult.php, tests/Functional/Console/Command/RunCommandTest.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php, tests/Functional/benchmarks/BenchmarkBench.php, tests/Unit/Benchmark/ParserTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Benchmark/SubjectBuilderTest.php, tests/Unit/Benchmark/parsertest/ParserCase.php, tests/Unit/Result/Dumper/XmlDumperTest.php
This PR aims to refactor reports to enable them to operate only groups of tables, for instance to create a summary report.
````
$config->addReport(array(
'name' => 'console_table',
'groups' => array('some_group_name'), // tables can be aggregated from multiple benchmarks
'aggregate' => 'table',
'deviation' => true,
'order' => array('rps' => 'desc'),
'rps' => true
));
````
=> Refactoring reports

CHANGELOG.md, README.md, lib/Benchmark/Runner.php, lib/Benchmark/Subject.php, lib/Benchmark/SubjectBuilder.php, lib/Console/Command/RunCommand.php, lib/Report/Cellular/CellularConverter.php, lib/Report/Cellular/Step/AggregateSubjectStep.php, lib/Report/Cellular/Step/ReplaceDescriptionTokensStep.php, lib/Report/Generator/BaseTabularReportGenerator.php, lib/Report/Generator/ConsoleTableReportGenerator.php, lib/Result/Dumper/XmlDumper.php, lib/Result/IterationsResult.php, lib/Result/Loader/XmlLoader.php, lib/Result/SubjectResult.php, tests/Functional/Console/Command/RunCommandTest.php, tests/Functional/benchmarks/BenchmarkBench.php, tests/Unit/Benchmark/ParserTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Benchmark/SubjectBuilderTest.php, tests/Unit/Benchmark/subject-builder-test/SubjectBuilderCase.php, tests/Unit/Benchmark/subject-builder-test/SubjectBuilderCaseInvalidParamProvider.php, tests/Unit/Report/Cellular/CellularConverterTest.php, tests/Unit/Report/Cellular/Step/ReplaceDescriptionTokensStepTest.php, tests/Unit/Result/Dumper/XmlDumperTest.php
Parameter sets are now unique for each Subject.
TODO:
- Allow token substitution in subject description for parameters
- `runs` are now not required, and should probably be removed if so.
- If above, remove `runs` aggregation step, consider making aggregation a boolean for reports.
Will fix #92
=> Refactoring parameters vs. subjects

CHANGELOG.md, README.md, examples/ArrayKeysBench.php, examples/CostOfReflectionBench.php, lib/Benchmark/Parser.php, lib/Benchmark/Runner.php, lib/Benchmark/Subject.php, lib/Benchmark/SubjectBuilder.php, lib/Report/Dom/PhpBenchXpath.php, lib/Report/Dom/xpath_functions.php, lib/Report/Generator/ConsoleTableGenerator.php, lib/Result/Dumper/XmlDumper.php, lib/Result/Loader/XmlLoader.php, lib/Result/SubjectResult.php, tests/Functional/Console/Command/ReportCommandTest.php, tests/Functional/Console/Command/RunCommandTest.php, tests/Functional/benchmarks/BenchmarkBench.php, tests/Functional/benchmarks/IsolatedBench.php, tests/Functional/benchmarks/IsolatedParametersBench.php, tests/Functional/benchmarks/IsolatedRevsBench.php, tests/Functional/report.xml, tests/Unit/Benchmark/ParserTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Benchmark/SubjectBuilderTest.php, tests/Unit/Benchmark/subject-builder-test/SubjectBuilderCase.php, tests/Unit/Report/Generator/ConsoleTableGeneratorTest.php, tests/Unit/Result/Dumper/XmlDumperTest.php, tests/Unit/Result/Loader/benchdump.xml
Consider removeing the "description" annotation from subjects and rely only on the classname and subject name to infer what benchmarks relate to.
=> Use the benchmark class name in results

.travis.yml, examples/phpbench.json, lib/Report/Dom/PhpBenchXpath.php, lib/Report/Generator/ConsoleTableGenerator.php, lib/Report/ReportManager.php, lib/Report/Tool/Assert.php, tests/Unit/Report/Dom/PhpBenchXpathTest.php, tests/Unit/Report/Generator/ConsoleTableGeneratorTest.php, tests/Unit/Report/ReportManagerTest.php, tests/Unit/Report/Tool/AssertTest.php
This PR aims to:
- Enable the definition of arbitrary rows
- Enable rows to be added dynamically (e.g. from the result of an XPath query or from a list of parameters
- Enable parameterable queries (e.g. `./iteration[parameter[@name="foo"]/@value = '{{ param }}'`)
- Enable cells to be created dynamically in the same way
- Enable cells to be formatted within their own configuration (and remove the `format` option).
````javascript
{
"rows": {
{
"cells": {
"one": "./expr",
"two": {
"expr": "./expr",
"format": ["%s%%"]
},
"three_{{ item }}": {
"expr": "./expr[name="{{ item }}"]",
"with_items": ["10", "100", "1000"]
}
},
"with_query": "//selector"
}
{
"cells": {
"one": "//total1",
"one": "//total2",
}
}
}
}
````
The above would add a row for each `//selector` and then a single row containing …
=> Changing to ansible-like iterators

docs/benchmark-runner.rst, lib/Extension/CoreExtension.php, lib/ProgressLogger/VerboseProgressLogger.php, tests/Functional/Console/Command/RunCommandTest.php
Adds new verbose logger:
````
PhpBench 0.5. Running benchmarks.
Using configuration file: examples/phpbench.json
\HashingBenchmark
>> benchMd5 [OK]
>> benchSha256 [OK]
>> benchSha1 [OK]
\StringSplitting
>> benchStrStrSubstr [OK]
>> benchPregMatch [OK]
>> benchExplode [OK]
\CostOfReflectionBench
>> benchMethodSet [OK]
>> benchPublicProperty [OK]
>> benchPublicReflection [OK]
>> benchPrivateReflection [OK]
>> benchNewClass [OK]
>> benchReflectionNewInstance [OK]
\CostOfCalling
>> benchCallWithoutParams [OK]
>> benchCallWithParams [OK]
\PhpBench\Tests\Functional\benchmarks\ArrayKeysBench
>> benchArrayKeyExists [OK]
>> benchIsset [OK]
>> benchInArray [OK]
Done (17 subjects, 146 iterations) in 8.26s
````
=> Verbose logger

docs/writing-benchmarks.rst, examples/ArrayKeysBench.php, examples/phpbench.json, examples/reports/array_keys.json, lib/Benchmark/Metadata/AbstractMetadata.php, lib/Benchmark/Metadata/Annotations/Skip.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Benchmark/Remote/ReflectionHierarchy.php, lib/Benchmark/Remote/Reflector.php, lib/Benchmark/Runner.php, lib/Report/Generator/tabular/aggregate.json, tests/Unit/Benchmark/RunnerTest.php
This PR adds a `NotApplicable` annotation which indicates that the benchmark is not applicable to the implementation under test. Possible alternative to #149 
This feature has the added benefit that `N/A` subjects are visible in reports.
=> Skip Annotation

lib/Benchmark/Executor/MicrotimeExecutor.php, lib/Benchmark/Executor/template/microtime.template, lib/Benchmark/ExecutorInterface.php, lib/Benchmark/Iteration.php, lib/Benchmark/IterationResult.php, lib/Benchmark/Runner.php, lib/Config/ConfigurableInterface.php, lib/Extension/CoreExtension.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php, tests/Unit/Benchmark/Executor/microtimetest/ExecutorBench.php, tests/Unit/Benchmark/RunnerTest.php
This PR makes the Executor polymorphic. The executor is responsible for executing the benchmark subject and retrieving the statistics about it.
Abstracting this makes it possible to implement different executors, such as an XDebug executor, a Blackfire executor, or whatever. Eventually even executors for different languages (JavaExecutor, PythonExecutor - but these would require alternate metadata drivers).
=> Polymorphic Executor

lib/Benchmark/Remote/Payload.php, lib/Benchmark/Remote/Reflector.php, tests/Unit/Benchmark/Remote/ReflectorTest.php, tests/Unit/Benchmark/Remote/reflector/ClassWithClassKeywords.php
Currently the Reflector class parses all the T_CLASS tokens, in addition to this returning the last declared class this will also include `Foobar::class` instances and return an empty string.
This fix will use the first instance of the `T_CLASS` token.
Fixes #174
=> Only parse the first class token

composer.json, docs/benchmark-runner.rst, docs/configuration.rst, docs/quick-start.rst, docs/reports.rst, docs/writing-benchmarks.rst, examples/phpbench.json, lib/Benchmark/ExecutorInterface.php, lib/Benchmark/Iteration.php, lib/Benchmark/IterationCollection.php, lib/Benchmark/Runner.php, lib/Console/Command/RunCommand.php, lib/Extension/CoreExtension.php, lib/Progress/Logger/DotsLogger.php, lib/Progress/Logger/NullLogger.php, lib/Progress/Logger/VerboseLogger.php, lib/Progress/LoggerInterface.php, lib/Report/Generator/tabular/aggregate.json, lib/Report/Generator/tabular/classes.json, lib/Report/Generator/tabular/iteration.json, tests/Functional/Report/Generator/TabularGeneratorTest.php, tests/System/RunTest.php, tests/System/output/html.html, tests/System/output/markdown.md, tests/System/report.xml, tests/Unit/Benchmark/IterationCollectionTest.php, tests/Unit/Benchmark/IterationTest.php, tests/Unit/Benchmark/RunnerTest.php
This PR introduces a new feature. Currently, if the system is unstable and there are anomalous timings, it is necessary to rerun the benchmarks until a suitable stability is reached.
This PR will introduce "Reject and Retry" on each iteration set. If an iteration deviates from the mean by more than a given value (e.g. 5%) then it is marked as being "rejected". Rejected iterations are then executed again and the deviations recalculated. This process will repeat until the requisite target stability is met.
This will enable more accurate timings at the expense of benchmarking time.
=> Iteration rejection and retry

docs/benchmark-runner.rst, examples/CostOfCallingBench.php, lib/Benchmark/CollectionBuilder.php, lib/Benchmark/Metadata/BenchmarkMetadata.php, lib/Benchmark/Runner.php, lib/Console/Command/RunCommand.php, tests/System/RunTest.php, tests/Unit/Benchmark/Metadata/BenchmarkMetadataTest.php
Renamed `subject` option to `filter` and made it act as a regex upon the fully expanded name (including the FQN of the class). Closes #123
=> Changed "subject" to "filter", fixes #123

composer.json, examples/ArrayKeysBench.php, lib/Extension/CoreExtension.php, lib/Report/Generator/AbstractTabularGenerator.php, lib/Report/Generator/TabularGenerator.php, lib/Report/Generator/tabular/aggregate.json, lib/Report/Generator/tabular/classes.json, lib/Report/Generator/tabular/iteration.json, tests/Functional/Report/Generator/TabularGeneratorTest.php
This PR introduces a new option to pretty print the parameters in the console report:
When using the `pretty_params` option:
False:
````
+-------------------------------------------------------------------------------------+------+-----+-----+----------+--------+-----------+-----------+
| params                                                                              | revs | its | rej | time     | memory | deviation | stability |
+-------------------------------------------------------------------------------------+------+-----+-----+----------+--------+-----------+-----------+
| {"hello":"Look \"I am using double quotes\"","goodbye":"Look 'I am use $dollars\""} | 5    | 5   | 0   | 7.4000μs | 544b   | 0.00%     | 20.00%    | …
```
=> Pretty print params

docs/reports.rst, lib/Benchmark/Executor/template/microtime.template, lib/Benchmark/Runner.php, lib/Report/Generator/tabular/aggregate.json, tests/Unit/Benchmark/RunnerTest.php
Use `memory_get_peak_usage` to get usage of entire iteration script nstead of the historical subtraction thing we are doing now.
=> Peak memory

docs/benchmark-runner.rst, docs/quick-start.rst, docs/writing-benchmarks.rst, lib/Benchmark/IterationCollection.php, lib/Benchmark/Runner.php, lib/Benchmark/SuiteDocument.php, lib/Console/Command/RunCommand.php, lib/Extension/CoreExtension.php, lib/Progress/Logger/DotsLogger.php, lib/Progress/Logger/NullLogger.php, lib/Progress/Logger/PhpBenchLogger.php, lib/Progress/Logger/VerboseLogger.php, lib/Progress/LoggerInterface.php, lib/Report/Generator/tabular/aggregate.json, tests/System/RunTest.php, tests/Unit/Benchmark/IterationCollectionTest.php, tests/Unit/Benchmark/RunnerTest.php
This PR adds some realtime statistics to the verbose logger and moves all of responsibility for the "non-report" output (including the `PHPBench Version x.x. Running Benchmarks` header) to the progress loggers.
This enables us to remove the `--quiet` flag - the same can now be achieved using `--progress=none`.
=> Detailed verbose logging

lib/Benchmark/Remote/Payload.php
I had escape this in order to get it working on my Windows box. My temp dir is in the user directory and there's a blank in the path. This fixes the problem and should work on *nix too in case someone has a blank in their temp path, probably never happens there though.
=> escape script path when calling command

composer.json, lib/Benchmark/IterationCollection.php, lib/PhpBench.php, tests/System/RunTest.php
This PR 
- adds a dependency on the Symfony Debug component, which provides an error handler.
- handles the situation (which can occur on Windows apparently) where all the iterations return 0 and we get a div by zero error.
=> Catch warnings and div by zero

docs/writing-benchmarks.rst, lib/Benchmark/Executor/BaseExecutor.php, lib/Benchmark/Executor/template/microtime.template, lib/Benchmark/Iteration.php, lib/Benchmark/IterationCollection.php, lib/Benchmark/Metadata/AbstractMetadata.php, lib/Benchmark/Metadata/Annotations/Warmup.php, lib/Benchmark/Metadata/DocParser.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Benchmark/Runner.php, lib/Benchmark/RunnerContext.php, lib/Console/Command/RunCommand.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php, tests/Unit/Benchmark/IterationCollectionTest.php, tests/Unit/Benchmark/IterationTest.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Benchmark/RunnerContextTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Util/TestUtil.php
This PR allows the code to be executed *x* times before measurements are taken. This is done via. the `@Warmup(x)` annotation.
=> Warmup feature

lib/Extension/CoreExtension.php, lib/Json/JsonDecoder.php, lib/Registry/Config.php, lib/Registry/Registry.php, tests/System/RunTest.php, tests/Unit/Json/JsonDecoderTest.php, tests/Unit/Registry/ConfigTest.php, tests/Unit/Registry/RegistryTest.php
- New JsonDecoder.
- Allows unquoted keys.
- Allows non encapsulated strings.
- Parses using JsonParse.
- Applies to all things that can be configured from the CLI with JSON.
From:
```bash
$ phpbench run --report='{"extends": "aggregate", "exclude": ["benchmark", "params"]}'
```
To:
```bash
$ phpbench run --report='extends: "aggregate", exclude: ["benchmark", "params"]'
$ phpbench run --executor='extends: "debug", times: [1, 2, 3, 4], spread: [0, 1, 2]'
```
=> Non-strict "JSON" support.

lib/Environment/Provider/Git.php, tests/Unit/Environment/Provider/GitTest.php
Checks to see if the GIT executable is available before attempting to use it.
Fixes #317
=> Git: Check to see if GIT exe is available.

lib/Benchmark/Runner.php, tests/Unit/Benchmark/RunnerTest.php
Fixes regression with not allowing the retry threshold to be set from the CLI.
=> Fixed overrides and added tests

lib/Benchmark/Remote/Reflector.php, tests/Unit/Benchmark/Remote/ReflectorTest.php, tests/Unit/Benchmark/Remote/reflector/ExampleClass2.php
Fixes #325 
The parser (copy and pasted from stackoverflow with attribution) was reading ahead for the `{` afert the class name before resolving it. Because we read in 20 line blocks, the `{` was not in the block with the class name.
This PR simply looks for any `T_STRING` after the `T_CLASS` token and assumes that that is the class name.
=> Fix class name detection

extensions/dbal/benchmarks/StorageBench.php, extensions/dbal/lib/Storage/Driver/Dbal/ConstraintVisitor.php, extensions/dbal/lib/Storage/Driver/Dbal/Persister.php, extensions/dbal/lib/Storage/Driver/Dbal/Repository.php, extensions/dbal/lib/Storage/Driver/Dbal/Schema.php, extensions/dbal/tests/Functional/Command/MigrateCommandTest.php, tests/Util/TestUtil.php
- Use atomic ID as PK for runs (but maintain UUID for external reference).
- Use `datetime` instead of `date` (MySQL will only store the data with `date`, Sqlite was storing the `datetime` as "expected").
- Batch insert iterations and variant params for all of suite.
=> Db improvements

docs/quick-start.rst, docs/storage.rst, extensions/dbal/lib/DbalExtension.php, extensions/dbal/lib/Storage/Driver/Dbal/Repository.php, extensions/dbal/lib/Storage/Driver/Dbal/Visitor/SqlVisitor.php, extensions/dbal/lib/Storage/Driver/Dbal/Visitor/TokenValueVisitor.php, extensions/dbal/tests/Functional/Storage/Driver/Dbal/HistoryIteratorTest.php, extensions/dbal/tests/Functional/Storage/Driver/Dbal/LoaderTest.php, extensions/dbal/tests/Functional/Storage/Driver/Dbal/RepositoryTest.php, extensions/dbal/tests/Unit/Storage/Driver/Dbal/Visitor/SqlVisitorTest.php, extensions/dbal/tests/Unit/Storage/Driver/Dbal/Visitor/TokenValueVisitorTest.php, lib/Console/Command/RunCommand.php, lib/Expression/Constraint/Comparison.php, lib/Report/Generator/TableGenerator.php, lib/Report/schema/report.xsd, tests/System/ReportOutputTest.php, tests/System/output/markdown.md, tests/Unit/Report/Generator/TableGeneratorTest.php
This PR introduces query token values which will be dynamically substituted before the query is transformed into an SQL statement.
This PR is adding the `latest` token on the `run` field. The token will be replaced with the UUID of the latest suite.
This allows a report to be quickly generated comparing the latest run against a known previous run:
```
$ phpbench query --query='run: "latest"' --query='run: "<some-uuid>"' --report='generator: table'
suite: 958456c7a631bb632ae9788e5e10f781ed37b7c4, date: 2016-03-09, stime: 10:38:07, vcs_branch: db_improvements
+------------------+-----+----------+----------+----------+----------+--------+
| subject          | its | best     | mean     | mode     | worst    | rstdev |
+------------------+-----+----------+----------+----------+----------+------ …
```
=> Query: token value support

.travis.yml, docs/environment.rst, docs/reports.rst, lib/Benchmark/Baseline/Baselines.php, lib/Benchmark/BaselineManager.php, lib/Environment/Provider/Baseline.php, lib/Extension/CoreExtension.php, phpbench.json.dist, tests/Unit/Benchmark/BaselineManagerTest.php, tests/Unit/Environment/Provider/BaselineTest.php
<strike>This PR is attempting to establish a good strategy for baseline measurements. It currently implements two new features, although one of them will probably be dropped in favor of the other.</strike>. This PR is now only abount the env provider. The other strategy is a [https://github.com/phpbench/phpbench/issues/372](separate feature).
The idea is to provide a way to better understand results taken from different machines, or anomalous results taken on the same machine.
Adds an Envrionment Provider which runs some very simple "benchmarks" (md5 10000 times, nothing 10000 times) and provides the time in microseconds.
All information made available through Environment providers are available in reports.
This provides a "better-than-nothing" indication of the performance of the machine …
=> Added baseline env provider

lib/Benchmark/Executor/template/benchmark_static_methods.template, lib/Benchmark/Executor/template/microtime.template, lib/Benchmark/Remote/template/parameter_set_extractor.template, lib/Benchmark/Remote/template/reflector.template, tests/System/RunTest.php, tests/System/bootstrap/conflicting.bootstrap
Bootstrap files are currently included directly into the remote scripts, which means that any variables they have can overwrite any previously declared variable.
This PR scopes the `require` in an anonymous function call.
=> Fixed bootstrap require scope

lib/Json/JsonDecoder.php, tests/Unit/Json/JsonDecoderTest.php, tests/Unit/Registry/ConfigurableRegistryTest.php
Introduces a JSON normalizer for "non-strict" JSON, replacing the original and flawed `preg_replace`.
Fixes #383
=> Non-strict JSON parser

docs/configuration.rst, extensions/xdebug/lib/Executor/XDebugExecutor.php, lib/Benchmark/Remote/Launcher.php, lib/Benchmark/Remote/Payload.php, lib/Benchmark/Remote/PayloadFactory.php, lib/Console/CharacterReader.php, lib/Console/Command/Handler/RunnerHandler.php, lib/Environment/Provider/Php.php, lib/Environment/Provider/template/php.template, lib/Extension/CoreExtension.php, lib/Math/Distribution.php, lib/Math/Kde.php, lib/PhpBench.php, tests/System/RunTest.php, tests/Unit/Benchmark/Executor/DebugExecutorTest.php, tests/Unit/Benchmark/Remote/LauncherTest.php, tests/Unit/Benchmark/Remote/PayloadFactoryTest.php, tests/Unit/Benchmark/Remote/PayloadTest.php, tests/Unit/Benchmark/Remote/ReflectorTest.php, tests/Unit/Environment/Provider/PhpTest.php, tests/Unit/Math/KdeTest.php
- Specify PHP binary
- Specify PHP ini settings
- Specify PHP wrapper
CLI:
```bash
$ phpbench run --php-binary=php7.0 --php-wrapper="blackfire run" --php-ini='memory_limit: 500, foobar: "foo"'
```
Or in configuration:
```yaml
{
"php_binary": "hhvm",
"php_wrapper": "tideways",
"php_ini": {
"memory_limit": 10
}
}
```
=> Allow configuration of launcher.

extensions/dbal/lib/Storage/Driver/Dbal/Persister.php, extensions/xdebug/lib/Executor/XDebugExecutor.php, lib/Benchmark/Executor/DebugExecutor.php, lib/Benchmark/Executor/MicrotimeExecutor.php, lib/Benchmark/Runner.php, lib/Model/Result/RejectionCountResult.php, lib/Model/ResultCollection.php, lib/Model/Variant.php, lib/Serializer/XmlDecoder.php, tests/System/RunTest.php, tests/Unit/Benchmark/Executor/DebugExecutorTest.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Model/ResultCollectionTest.php, tests/Unit/Progress/Logger/BlinkenLoggerTest.php, tests/Unit/Progress/Logger/HistogramLoggerTest.php
- The current behavior breaks the retry threshold feature which relies
upon overwriting previously set results.
- Replaces `replaceResult` and `addResult` with `setResult`.
- Improves the debug executor so that we can test the retry-threshold feature.
Fixes #423
=> Allow results to be overridden.

composer.json
Allow this dependency to be updated while avoiding a compatibility issue with
HHVM present in lstrojny/functional-php:1.2.1. This issue is fixed in 1.2.3.
=> Adjust lstrojny/functional-php dependency version

extensions/xdebug/lib/Command/Handler/OutputDirHandler.php, lib/Storage/UuidResolver.php, tests/Unit/Storage/UuidResolverTest.php
=> Throw exception if trying to resolve latest UUID when no history.

extensions/xdebug/tests/System/XDebugTestCase.php, tests/System/SystemTestCase.php, tests/System/env/config_dist/phpbench.json.dist, tests/System/env/config_valid/phpbench.json
Use a workspace directory instead of arbitrarily cleaning up the repository.
=> Cleaned up test debris

.travis.yml, docs/report-generators.rst, docs/reports.rst, lib/Extension/config/class/main.json, lib/Report/Generator/TableGenerator.php, tests/Unit/Report/Generator/TableGeneratorTest.php
Currently the diff column uses a strange metric, for example:
```
$diff = (100 / $currentMean) * ($currentMean - $lowestMean);
```
Which gives ... a result where large differences between two numbers
can be expressed as 90% vs 95% reative to a much smaller (-10x) min value.
This PR replaces this with:
```
$diff = $currentMean / $lowestMean;
```
Givng _x_ is _n_ times slower than the lowest _x_.
```
+-----------+----------+----------+----------+----------+--------+-------+
| benchmark | mean     | mode     | worst    | stdev    | rstdev | diff  |
+-----------+----------+----------+----------+----------+--------+-------+
| KdeBench  | 0.5031ms | 0.5277ms | 0.5472ms | 0.0504ms | 10.02% | 1.00x |
| KdeBench  | 0.7134ms | 0.6009ms | 0.9685ms | 0.1476ms | 20.69% | 1.42x |
| KdeBench  | 1.2471ms …
```
=> Use "x times faster than" metric for "diff" column.

.travis.yml, composer.json
5.5 is no longer supported and functional-php requires at least 5.6
Fixes #441
=> Bumped minimum requirement to 5.6

docs/extensions/xdebug.rst
There must be an array instead of object
=> Fixed type in json config

docs/configuration.rst
To avoid following error "Could not decode return value from script from template" we must disable any output from blackfire command
=> Blackfire output log lead to exception

docs/storage.rst
=> Fix: Actually use JSON in configuration example

.travis.yml, composer.json
This PR
Somewhat related to #484.
💁‍♂️ For reference, see 
* https://getcomposer.org/doc/03-cli.md#validate
* https://getcomposer.org/doc/04-schema.md#suggest
=> Enhancement: Validate composer.json in before_install section

lib/Report/Generator/Table/Sort.php, lib/Report/Renderer/XsltRenderer.php, tests/System/SystemTestCase.php, tests/Unit/Report/Generator/Table/SortTest.php, tests/Unit/Report/Renderer/AbstractRendererCase.php, tests/Unit/Serializer/XmlDecoderTest.php
=> Fix: Case mismatch in method call or class name

extensions/xdebug/lib/Executor/ProfileExecutor.php, extensions/xdebug/lib/Executor/TraceExecutor.php, extensions/xdebug/lib/Executor/XDebugTraceExecutor.php, extensions/xdebug/tests/Unit/Executor/TraceExecutorTest.php, lib/Benchmark/Executor/MicrotimeExecutor.php, lib/Benchmark/Remote/Launcher.php, lib/Benchmark/Remote/Payload.php, phpbench.json.dist, tests/Unit/Benchmark/BaselineManagerTest.php, tests/Unit/Benchmark/Remote/LauncherTest.php, tests/Unit/Benchmark/Remote/PayloadTest.php
Disallow the replacement of the PHP config.
Currently whenever `setPhpConfig` is called on the payload, the configuration is replaced, overwriting any user configuration (either from config or the CLI).
This PR changes the behavior to always merge _onto_ the existing user configuration.
Fixes #481 and partly #488
=> Only allow "merging" of PHP config

docs/configuration.rst, docs/quick-start.rst, lib/Benchmark/Executor/BaseExecutor.php, lib/Benchmark/Executor/template/health_check.template, lib/Benchmark/ExecutorInterface.php, lib/Benchmark/Remote/IniStringBuilder.php, lib/Benchmark/Remote/Launcher.php, lib/Benchmark/Remote/Payload.php, lib/Benchmark/Remote/PayloadFactory.php, lib/Benchmark/Runner.php, lib/Console/Command/Handler/RunnerHandler.php, lib/Environment/Provider/Php.php, lib/Environment/Provider/template/php.template, lib/Extension/CoreExtension.php, lib/PhpBench.php, tests/System/RunTest.php, tests/Unit/Benchmark/Remote/IniStringBuilderTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Environment/Provider/PhpTest.php
Added option to disable PHP ini:
**NOTE**: Unforfortunately PHPBench currently requires the JSON extension to be loaded in the remote process - it has to be explicitly enabled, we could automatically enable it, but this might causes WTFs. Currently we just throw a helpful exception.
I think in the future we should change this and the remote processes should just return formatted plain text.
So a configuration might look like this:
```javascript
{
"bootstrap": "vendor/autoload.php",
"path": "benchmarks",
"php_disable_ini": true,
"php_config": {
"extension": [ "json.so" ]
}
}
```
=> Disable php ini

.travis.yml
This modification adds the following flags for the CLI application:
- `o`: Optimize autoloader
- `a`: Autoload classes from the classmap only
See https://getcomposer.org/doc/articles/autoloader-optimization.md for additional information.
=> Optimization flags added for the application

lib/Benchmark/Runner.php, tests/Unit/Model/SuiteTest.php, tests/Unit/Model/SummaryTest.php, tests/Unit/Registry/ConfigurableRegistryTest.php
=> Fix: Case mismatch

bin/phpbench
=> Fix: Remove unnecessary parentheses

lib/Benchmark/Remote/Reflector.php, lib/Serializer/XmlDecoder.php, lib/Serializer/XmlEncoder.php, tests/Unit/Benchmark/Remote/ReflectorTest.php, tests/Unit/Benchmark/Remote/reflector/ExampleClass.php, tests/Unit/Serializer/XmlTestCase.php
While first attempt to bench something using the @ParamProviders annotation...I got InvalidArgumentException messages such as : 
Parameter values must be scalar. Got "NULL" 
Parameters must be either scalars or arrays, got: NULL
But I want my bench method to have null values into array of parameters
So I change few lines into the code and all went as excpected.
I have not check further impact in my modifications but I really need this feature.
=> Allowing NULL values using ParamProviders

.styleci.yml
=> Fix: Remove apparently unused configuration for StyleCI

.travis.yml, .travis/xdebug.sh
This PR
Blocks #568.
💁‍♂️ The idea is this:
* there is no need to run `php-cs-fixer` or `phpstan` on every *test* build
* there is probably no need to run a static analysis with `phpstan` when `php-cs-fixer` detected code style isses
* there is probably no need to run tests with `phpunit` when `php-cs-fixer` and `phpstan` detected code style or static analysis issues
* it will be easier (and more explicit) to add more builds to the matrix (also see #568)
For reference, see https://docs.travis-ci.com/user/build-stages.
=> Enhancement: Switch to using build stages on Travis

.php_cs.dist
This PR
💁‍♂️ For reference, see https://github.com/friendsofphp/php-cs-fixer/tree/v2.13.1#usage:
>**phpdoc_separation** [`@Symfony`]
>
>Annotations in PHPDoc should be grouped together so that annotations of the same type immediately follow each other, and annotations of a different type are separated by a single blank line.
❗️ This code style is basically in use already, but enabling the fixer ensures that it stays that way.
=> Enhancement: Enable phpdoc_separation fixer

composer.json, docs/configuration.rst, docs/introduction.rst, docs/quick-start.rst, extensions/xdebug/lib/Command/ProfileCommand.php, extensions/xdebug/lib/Command/TraceCommand.php, extensions/xdebug/lib/Executor/TraceExecutor.php, extensions/xdebug/lib/Executor/XDebugTraceExecutor.php, phpunit.xml.dist
This PR
💁‍♂️ I have naturally used the former myself, but @derickr uses the latter on https://xdebug.org:
=> Fix: Extension is called Xdebug

.php_cs.dist, extensions/dbal/lib/Storage/Driver/Dbal/Persister.php, extensions/xdebug/lib/Command/ProfileCommand.php, extensions/xdebug/lib/Command/TraceCommand.php, lib/Benchmark/Metadata/BenchmarkMetadata.php, lib/Benchmark/Metadata/SubjectMetadata.php, lib/Model/Benchmark.php, lib/Model/Subject.php, lib/Progress/Logger/AnsiLogger.php, lib/Serializer/XmlEncoder.php, tests/Unit/Storage/Driver/Xml/HistoryIteratorTest.php
This PR
Follows #572.
💁‍♂️ For reference, see https://github.com/friendsofphp/php-cs-fixer/tree/v2.13.1#usage:
>**no_unused_imports** [`@Symfony`]
>
>Unused use statements must be removed.
=> Enhancement: Enable no_unused_imports fixer

.travis.yml
This PR
See https://travis-ci.org/phpbench/phpbench/builds/472739856:
See https://travis-ci.org/phpbench/phpbench/builds/473001742:
=> Enhancement: Explicitly test against lowest and highest versions of dependencies

.php_cs.dist, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Model/BenchmarkTest.php, tests/Unit/Serializer/XmlTestCase.php
This PR
Follows #572.
💁‍♂️ For reference, see https://github.com/friendsofphp/php-cs-fixer/tree/v2.13.1#usage:
>**ordered_imports**
>
>Ordering use statements.
>
>Configuration options:
>
>* `imports_order` (`array`, `null`): defines the order of import types; defaults to `null`; DEPRECATED alias: `importsOrder`
>* `sort_algorithm` (`'alpha'`, `'length'`, `'none'`): whether the statements should be sorted alphabetically or by length, or not sorted; defaults to `'alpha'`; DEPRECATED alias: `sortAlgorithm`
=> Enhancement: Enable ordered_imports fixer

lib/Formatter/Format/TimeUnitFormat.php, lib/Util/TimeUnit.php, tests/Unit/Util/TimeUnitTest.php
the (newly introduced) casting prevented the mean micro-second time from
being shown in the reports.
=> fixes incorrect int cast

lib/Benchmark/Baseline/Baselines.php
Fix new PHP 7.4 notice on Baseline.php leading to the crash.
https://bugs.php.net/bug.php?id=78482
=> Baseline.php : Fix PHP 7.4 notice on fgets()

lib/Benchmark/Remote/Payload.php
While running PHPBench, I ran into this error:
```
PhpBench @git_tag@. Running benchmarks.
Using configuration file: /home/travis/build/thecodingmachine/tdbm/phpbench.json
In Payload.php line 201:
Notice: unserialize(): Error at offset 0 of 776 bytes  
```
The unserialize notice is causing phpbench to halt (because of the error handler that treats notices as fatal errors).
The message is quite unhelpful. What I wanted was this nice exception to be triggered:
https://github.com/moufmouf/phpbench/blob/d58804dcb85759d6babf8e8208a2b71fa017f9af/lib/Benchmark/Remote/Payload.php#L207-L211
So I simply silenced the unserialize warnings. That way, when an error occurs, it is correctly caught by the code and a nice exception is thrown. I can now see the issues in my code more clearly:
```
PhpBench …
```
=> Silencing unserialize notice to benefit from full error message

composer.json, lib/Benchmark/Runner.php, lib/Console/Command/RunCommand.php, tests/Unit/Benchmark/RunnerTest.php
@julien-boudry reverting this for now as there are breaking BC breaks (e.g. process requires array not string). I assumed wrongly that the CI would test v5, but as it's still RC it wasn't picked up (and php-cs-fixer requires 4x)
=> Revert "Symfony 5"

lib/Executor/Benchmark/TemplateExecutor.php, lib/Executor/Benchmark/template/memory.template, lib/Executor/Benchmark/template/microtime.template
* parse `parameters` directly into parameter positions -> no variable and parameter condition needed
* removed function `backmark` and instead execute the banchmark in place -> this reduces the function call stack by one
PS: I would like to introduce a condition for hrtime (see #591) to not need to call time function dynamically which would increase time function call overhead.
=> reduced time/mem centric executor overhead

benchmarks/Macro/ReportBench.php, lib/Report/Generator/TableGenerator.php, lib/Serializer/XmlDecoder.php
It seems that computers are getting faster and this is uncovering some of the bad typing in Phpbench.
This should fix the division by zero issue (#626 )
=> Cast decoded stats to (float) fixes #626

lib/Benchmark/Remote/template/parameter_set_extractor.template
The method is an instance method so needs to be tested against the instance.
Pretty sure this is a tidy up for PHP 8.
=> Correct testing of whether instance method is callable.

docs/introduction.rst
Athletic is no longer maintained and shouldn't be considered an alternative.
=> Remove the reference to Athletic from the docs

composer.json, docs/book.rst, docs/faq.rst, docs/guides.rst, docs/installing.rst, lib/Model/Summary.php, lib/Progress/Logger/PhpBenchLogger.php, phpstan.neon, tests/Unit/Model/SummaryTest.php
Shows the xdebug / opcache status when running benchmarks:
```
PHPBench @git_tag@ running benchmarks...
with configuration file: /home/daniel/www/phpbench/phpbench/phpbench.json.dist
with PHP version 7.4.3, xdebug ✔, opcache ❌
```
=> Show xdebug opcache status in header

CHANGELOG.md, extensions/xdebug/lib/Executor/ProfileExecutor.php, lib/Benchmark/Runner.php, lib/Executor/Benchmark/DebugExecutor.php, lib/Executor/Benchmark/TemplateExecutor.php, lib/Executor/BenchmarkExecutorInterface.php, lib/Executor/CompositeExecutor.php, lib/Executor/ExecutionResults.php, lib/Model/Result/TimeResult.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Executor/Benchmark/DebugExecutorTest.php, tests/Unit/Executor/Benchmark/MicrotimeExecutorTest.php
Changes the Executor API to ensure that something is returned than executors having to set the result on the iteration itself.
=> Execution results

CHANGELOG.md, composer.json, extensions/xdebug/lib/Command/ProfileCommand.php, extensions/xdebug/lib/Executor/ProfileExecutor.php, extensions/xdebug/lib/XDebugUtil.php, extensions/xdebug/tests/Unit/XDebugUtilTest.php, lib/Benchmark/Exception/RetryLimitReachedException.php, lib/Benchmark/Metadata/SubjectMetadata.php, lib/Benchmark/Runner.php, lib/Executor/Benchmark/DebugExecutor.php, lib/Executor/Benchmark/TemplateExecutor.php, lib/Executor/Benchmark/TestExecutor.php, lib/Executor/BenchmarkExecutorInterface.php, lib/Executor/CompositeExecutor.php, lib/Executor/ExecutionContext.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Executor/Benchmark/DebugExecutorTest.php, tests/Unit/Executor/Benchmark/MicrotimeExecutorTest.php, tests/Util/TestUtil.php
- Executors accept a single, immutable `ExecutionContext` instead of the
mutable `SubjectMetadata` and `Iteration`
- Refactored the tests around this.
=> Execution context

docs/assertions.rst
The last column was always empty:
=> Fix: CSV table in documentation

docs/environment.rst, docs/reports.rst
Only 1 backslash is needed when highlighted using two backticks
This was reported by DOCtor-RST
=> Enhancement: Better readability

.travis.yml
cc @Jeckerson we disabled Xdebug during the build previously on Travis -- not sure why (@localheinz ?)
=> Do not deploy to GH releases with Travis

CHANGELOG.md, examples/Benchmark/Micro/HashingBench.php, examples/OutputTest/OutputTestBench.php, lib/Extension/CoreExtension.php, lib/Model/ErrorStack.php, lib/Model/Summary.php, lib/Progress/Logger/PhpBenchLogger.php, tests/Benchmark/ExpresionParserBench.php, tests/Unit/Model/SuiteTest.php, tests/Unit/Model/SummaryTest.php, tests/Unit/Progress/Logger/PhpBenchLoggerTest.php
Show PHPUnit style success indicator when finishing the run:
... and removes some of the less interesting information from this summary line (nb. itreations and revs).
=> Improve error reporting

.travis/before-deploy.sh, .travis/xdebug.sh
Small fixes for shell script static analysis, [Shell Check](https://github.com/koalaman/shellcheck).
- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086): Double quote to prevent globbing and word splitting.
- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154): Throw error if the referenced variable is  not assigned.
=> refactor: SC2086 and SC2154 error of shellcheck

.github/workflows/release-phar.yml
Due Github Actions updated PHP version to the latest (8.0) in their images, latest release failed and didn't uploaded `.phar` into it.
Working example - https://github.com/Jeckerson/phpbench/runs/1622156785?check_suite_focus=true
=> Fix .phar compilation during release

CHANGELOG.md, lib/Console/Command/RunCommand.php, lib/Extension/CoreExtension.php, lib/Math/Ratio.php, lib/Progress/Logger/BlinkenLogger.php, lib/Progress/Logger/DotsLogger.php, lib/Progress/Logger/HistogramLogger.php, lib/Progress/Logger/PhpBenchLogger.php, lib/Progress/VariantSummaryFormatter.php, lib/Util/TimeUnit.php, tests/Benchmark/ExpressionParserBench.php, tests/System/RunTest.php, tests/Unit/Progress/Logger/BlinkenLoggerTest.php, tests/Unit/Progress/Logger/DotsLoggerTest.php, tests/Unit/Progress/Logger/HistogramLoggerTest.php, tests/Unit/Progress/Logger/LoggerTestCase.php, tests/Unit/Progress/Logger/PhpBenchLoggerTest.php, tests/Unit/Progress/Logger/TravisLoggerTest.php, tests/Unit/Progress/Logger/VerboseLoggerTest.php, tests/Unit/Progress/VariantSummaryFormatterTest.php, tests/Util/TestUtil.php
Improve the progress output when using a baseline (and make the output more succinct)
- By default only show the mode and relative deviation (the KDE mode has consistently been a better indicator than the mean)
- When baseline is present, show comparison in output
- Will allow custom formatting (e.g. add more fields to the output)
=> Improve progress output when baseline (reference) is used

lib/Assertion/ParameterProvider.php, lib/Expression/NodePrinter/DisplayAsPrinter.php, lib/Extension/ExpressionExtension.php, lib/Report/Generator/ExpressionGenerator.php, tests/Unit/Expression/Parselet/DisplayAsParseletTest.php, tests/Unit/Expression/ParseletTestCase.php
- Do not use decorated printer for error messages
- Allow time unit to be inferred from parameters (i.e. permit `@OutputTimeUnit` to be passed to the expression printer)
=> Minor Bug Fixes

docs/expression.rst, examples/Expression/time_unit_3, lib/Expression/Ast/DisplayAsNode.php, lib/Expression/Parselet/DisplayAsParselet.php, lib/Expression/Precedence.php, tests/Unit/Expression/Parselet/DisplayAsParseletTest.php
Necessary for the `OutputTimePrecision` annotation to have any meaning after merging the new expression report.
=> Add support for specifying display precision in expr language

CHANGELOG.md, lib/Benchmark/Metadata/Driver/ConfigDriver.php, lib/Extension/CoreExtension.php, phpbench.json.dist, tests/Benchmark/Assertion/AssertionProcessorBench.php, tests/Benchmark/Expression/ParserBench.php, tests/Benchmark/IntegrationBenchCase.php, tests/Benchmark/Progress/VariantSummaryFormatterBench.php, tests/Benchmark/Report/Generator/ExpressionGeneratorBench.php, tests/Unit/Benchmark/Metadata/Driver/ConfigDriverTest.php, tests/Unit/Extension/CoreExtensionTest.php
Allow certain metadata to be set in the config, e.g. `iterations`, `revs`, `time_unit` etc.
=> Config runner config

CHANGELOG.md, docs/report-generators.rst, examples/Command/report-generators-data, lib/Environment/Provider/TestProvider.php, lib/Extension/CoreExtension.php, lib/Report/Transform/SuiteCollectionTransformer.php
For the purposes of disabling them in approval tests, possibly also for
increasing the speed of the tests.
This allows, for example, for the PHP version to be included in the report:
```
ParserBench-benchEvaluate
+-----------+--------+--------+-------------+----------------+----------------+
| tag       | xdebug | php    | set         | mode           | rstdev         |
+-----------+--------+--------+-------------+----------------+----------------+
| master    |        | 7.4.14 | comp. w/tol | 0.073ms        | ±2.24%         |
| <current> | false  | 8.0.1  | comp. w/tol | 0.075ms +2.79% | ±1.96% -12.33% |
| master    |        | 7.4.14 | comp.       | 0.065ms        | ±2.25%         |
| <current> | false  | 8.0.1  | comp.       | 0.064ms -2.31% | ±2.17% -3.61%  | …
```
=> Make collected environment data  available in reports

CHANGELOG.md, lib/Environment/Provider/template/opcache.template, lib/Serializer/XmlDecoder.php, lib/Serializer/XmlEncoder.php, tests/Unit/Serializer/XmlDecoderTest.php, tests/Unit/Serializer/XmlTestCase.php
All env values were previously decoded as strings - which made the env report look inconsistent.
=> Preserve the types of env metrics in storage

docs/benchmark-runner.rst, docs/faq.rst, lib/Console/Command/EvaluateCommand.php, lib/Expression/Evaluator/PrettyErrorEvaluator.php, lib/Expression/Exception/SyntaxError.php, lib/Extension/ExpressionExtension.php, lib/Extension/RunnerExtension.php, lib/Progress/Logger/DotsLogger.php, lib/Util/TextTruncate.php, tests/System/EvalCommandTest.php, tests/System/RunTest.php, tests/Unit/Expression/Exception/SyntaxErrorTest.php, tests/Unit/Extension/RunnerExtensionTest.php, tests/Unit/Progress/Logger/DotsLoggerTest.php, tests/Unit/Util/TextTruncateTest.php
- Renamed `travis` progress logger to `plain`
- Removed references to the (travis) `CONTINUOUS_INTEGERATION`  env var.
- Updated SyntaxError to truncate the output.
=> Minor fixes

lib/Extension/CoreExtension.php, lib/Logger/ConsoleLogger.php, lib/Report/Generator/ExpressionGenerator.php, tests/Unit/Logger/ConsoleLoggerTest.php
Simply shows `ERR` in report cells that errored, and ensures that ERROR level log messages are shown (as the ERR messages are logged)
=> Imporve expr errors in report

CHANGELOG.md, composer.json, lib/Console/Application.php, lib/PhpBench.php, lib/Progress/Logger/PhpBenchLogger.php, lib/Serializer/XmlEncoder.php, tests/Unit/Serializer/XmlEncoderTest.php
Use Package Versions to determine PHPBench version if not using a PHAR, fixes #810
=> Package versions

CHANGELOG.md, lib/Console/Command/Handler/RunnerHandler.php, tests/System/RunTest.php
Allow multiple paths to be specified from the CLI. Multiple paths are
currently supported in configuration, this will enable passing multiple paths
as arguments to the `run` command.
=> [feature] Allow Multiple Paths to be specified from CLI

CHANGELOG.md, lib/Report/Generator/ExpressionGenerator.php
`microseconds` was hardcoded as the default instead of `time` which will automatically determine the unit
=> improvement: Use automatic time unit for expression report

phpbench.json.dist
The `phpbench.json.dist` file has the `"runner.php_config"` key duplicated.
Technically the JSON specification does not make any mention of duplicate keys being invalid or valid, but this could cause problems in some JSON libraries implementations.
=> Fix duplicated key "runner.php_config" on phpbench.json.dist

lib/Expression/Ast/DelimitedListNode.php, lib/Expression/Func/MaxFunction.php, lib/Expression/Func/MeanFunction.php, lib/Expression/Func/MinFunction.php, lib/Expression/Func/ModeFunction.php, lib/Expression/Func/RStDevFunction.php, lib/Expression/Func/StDevFunction.php, lib/Expression/Func/VarianceFunction.php, lib/Report/Generator/ComponentGenerator.php, tests/Unit/Expression/Func/MaxFunctionTest.php, tests/Unit/Expression/Func/MeanFunctionTest.php, tests/Unit/Expression/Func/MinFunctionTest.php, tests/Unit/Expression/Func/ModeFunctionTest.php, tests/Unit/Expression/Func/RStDevFunctionTest.php, tests/Unit/Expression/Func/StDevFunctionTest.php, tests/Unit/Expression/Func/VarianceFunctionTest.php
Need to consider this and apply it also to other aggregate functions.
=> Fix mode() when population has NULL values

CHANGELOG.md, composer.json, docs/configuration.rst, lib/Benchmark/BenchmarkFinder.php, lib/Benchmark/Metadata/AnnotationReader.php, lib/Benchmark/Metadata/MetadataFactory.php, lib/Extension/RunnerExtension.php, lib/Logger/ConsoleLogger.php, tests/Benchmark/Expression/ParserFoo.php, tests/Unit/Benchmark/BenchmarkFinderTest.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Benchmark/Metadata/Exception/CouldNotLoadMetadataException.php, tests/Unit/Benchmark/findertestnobenchsuffix/NoBenchSuffix.php
This "bug" has been present since 2016.
It is [documented](https://phpbench.readthedocs.io/en/latest/quick-start.html#create-a-benchmark) that we only run files suffixed with `Bench.php` and this was completely my understanding, however since version 0.10.0 PHPBench will take into account any PHP file in the benchmark `path`.
This is not good because:
- It will try and read annotations from non-benchmark classes (https://github.com/phpbench/phpbench/issues/643)
- People who read the documentation (or listened to anything I said) would not expect this behavior.
- The "reflector" will execute code in non `*Bench` files, which increases the chance of unintentional code execution.
Fixing it however means a non-fatal change in behavior:
- Anybody depending on benchmark classes not having the …
=> Fix benchmark finder to only pick up *Bench files

docs/quick-start.rst
In the example, it extends the 'aggregate' report, not the 'default'.
=> Fix error in documentation

lib/Console/Command/LogCommand.php, lib/Executor/Benchmark/LocalExecutor.php, lib/Executor/Benchmark/TemplateExecutor.php, lib/Executor/ExecutionContext.php, lib/Report/ComponentGenerator/BarChartAggregateComponentGenerator.php, tests/Unit/Report/ComponentGenerator/BarChartAggregateComponentGeneratorTest.php
Add B/C accessor for parameter set and fix failing `assert` calls, adding a test for the case where the Y-expression evaluates to a non-numeric value.
=> B c parameter execution context

lib/Reflection/RemoteReflector.php
PHP 8.0 introduced a new token for fully qualified namespaces, represented
by the constant `T_NAME_QUALIFIED`, which in that version had the integer representation of 314.
With the upcoming version 8.1, the token received a different integer representation, thus breaking the logic with the previously hardcoded integer value.
Closes issue https://github.com/phpbench/phpbench/issues/905
=> Use token for full namespace whenever available

.php_cs.dist, CHANGELOG.md, lib/Console/Command/RunCommand.php, lib/Expression/Ast/ErrorNode.php, lib/Expression/NodePrinter/DisplayAsPrinter.php, tests/System/RunTest.php, tests/Unit/Expression/Parselet/DisplayAsParseletTest.php
Do not show reports if there were errors, as there is too much noise.
=> Do not show reports if there were errors

lib/Color/Gradient.php, lib/Data/DataFrame.php, lib/Data/DataFrames.php, lib/Data/Row.php, lib/Environment/Information.php, lib/Expression/Exception/SyntaxError.php, lib/Math/Distribution.php, lib/Model/ParameterSets.php, lib/Model/ParameterSetsCollection.php, lib/Model/Variant.php, lib/Reflection/ReflectionHierarchy.php, lib/Registry/Config.php, lib/Remote/Payload.php, lib/Report/Model/Reports.php, lib/Report/Model/Table.php, lib/Report/Model/TableRow.php, lib/Serializer/XmlEncoder.php, lib/Storage/Driver/Fake/FakeHistoryIterator.php, lib/Storage/Driver/Xml/HistoryIterator.php
I am not 100% certain of all of these, but this at least gets my tests locally to pass, except for those that require the git binary.  My container doesn't have git in it so that fails.  At least I don't get any deprecation warnings.
This works only with the updated Dom library from this PR: https://github.com/phpbench/dom/pull/4
(I have edits allowed, so feel free to fix up anything you'd like done differently. I won't take offense. :smile: )
=> Fix PHP 8.1 deprecations

.github/workflows/ci.yaml, composer.json, extensions/xdebug/lib/Command/ProfileCommand.php, extensions/xdebug/tests/System/XDebugTestCase.php, phpbench.json
This PR adds a CI run for PHP 8.1 and drops support for PHP 7.2
=> Enable 8.1 in GH actions

CHANGELOG.md, lib/Benchmark/Metadata/BenchmarkMetadata.php, lib/Console/Command/Handler/RunnerHandler.php, lib/Console/Command/Handler/SuiteCollectionHandler.php, lib/Console/Command/ReportCommand.php, lib/Model/Benchmark.php, lib/Model/Subject.php, lib/Model/Suite.php, lib/Model/SuiteCollection.php, tests/System/ReportTest.php, tests/Unit/Model/SuiteTest.php, tests/Util/BenchmarkBuilder.php, tests/Util/SubjectBuilder.php, tests/Util/SuiteBuilder.php, tests/Util/VariantBuilder.php
Support filtering reports. Filters that apply to a bechmark run will also be applied to any other suite which is used as as a reference.
Additionally it adds a full set of benchmark "model" test builders to avoid having to use mocks.
=> Filter reports in addition to the run

README.md
This will allow users to click the 'copy to clipboard' button in the github interface
=> Make it easy to copy composer install command on github

composer.json
Currently, Packagist and Composer believe that the master branch contains version 1.1-dev. But since that branch is ahead of the 1.2.x releases, that seems to be a lie. 🙂
=> Tell composer that the master branch is 1.2-dev

lib/Color/Gradient.php, tests/Unit/Expression/Theme/Util/GradientTest.php
There are parts of the application that would send float values to
this method.
This change intends to address a PHP Deprecation in PHP 8.1.
=> Allow float value instead of int

docs/configuration-prelude.rst
This PR resolves a small typo in the word configuration.
=> [Fix] CONFIGURATION PRELUDE: Typo in `configuration`

lib/Attributes/Assert.php, tests/Unit/Attributes/AssertTest.php
Fix for missing `Attribute::IS_REPEATABLE` for the `Assert` attribute see #997
=> #997 make Assert repeatable for PHP8+ attributes

CHANGELOG.md, composer.json, lib/Config/Processor/IncludeGlobProcessor.php, lib/Util/PathNormalizer.php
Use `webmozrt/glob` instead of PHP's `glob` to enable `/**/` to wildcard on directory levels.
Fixes #1004
=> Fix expected glob behavior

extensions/xdebug/lib/Command/ProfileCommand.php, extensions/xdebug/lib/Executor/ProfileExecutor.php, extensions/xdebug/lib/XDebugExtension.php, extensions/xdebug/lib/XDebugUtil.php, extensions/xdebug/tests/Unit/XDebugUtilTest.php, phpstan.neon.dist
Xdebug 3.1 enables compression of the cachegrind files automatically so the extension of the output by default is not .cachegrind but .cachegrind.gz.
This patch adds a check to see if compression is enabled and then uses .cachegrind.gz instead of .cachegrind as extension.
=> Detect xdebug.use_compression and set correct extension

.github/workflows/documentation.yaml
Using v3 seems to be the correct move: https://github.com/sphinx-doc/sphinx/blob/v5.3.0/Makefile#L1
This small PR should allow me to achieve non-first-contributor status, and no longer require you pressing a button for me to be able to run workflows.
=> Address Package name change

lib/Util/TimeUnit.php
Passing this arguments on benchmark runs:
```
php vendor/bin/phpbench run src/Tests/Benchmark/Algorithm1Bench.php --report=aggregate --retry-threshold=5 --progress=blinken
```
It returns this warning for each time you put on the annotation `Revs`.:
```
Deprecated: number_format(): Passing null to parameter #2 ($decimals) of type int is deprecated in /var/www/html/vendor/phpbench/phpbench/lib/Progress/Logger/PhpBenchLogger.php on line 195
```
This should fix it. :)
=> Fix: removing deprecation warning when passing --progress=blinken

composer.json
I almost didn't find you. 🙂 Composer keywords appear as filterable tags on Packagist, e.g., [#performance](https://packagist.org/search/?tags=performance).
=> Add Composer keywords for findability on Packagist

docs/customisation.rst, docs/customisation/environment-provider.rst, docs/customisation/extension.rst, examples/Extension/AcmeExtension.php, examples/Extension/Environment/HomeProvider.php
I worked on adding an [environment provider for MongoDB benchmarks](https://github.com/mongodb/mongo-php-library/blob/4e581cf0c5f9a901b189f1b247a3a7759be18d02/benchmark/Extension/EnvironmentProvider.php) and found some missing pieces of documentation.
This needs to be reviewed because I just started working with PHPBench. But I think this new documentation will be helpful if someone needs to create a custom env provider.
Also, I added the namespaces to the base extension example. I was disturbed to not knowing the actual class of `ExtensionInterface`.
=> Add documentation about adding an environment provider

lib/Util/MemoryUnit.php, tests/Unit/Util/MemoryUnitTest.php
There are two methods in `lib/Util/MemoryUnit.php`:
https://github.com/phpbench/phpbench/blob/5f12699b84926d7674fc5ad54e319a7556d0fc50/lib/Util/MemoryUnit.php#L90-L94
and
https://github.com/phpbench/phpbench/blob/5f12699b84926d7674fc5ad54e319a7556d0fc50/lib/Util/MemoryUnit.php#L118-L122
`$unit` is nullable and can be returned as is. But return type of the methods is string. So if `$unit === null` we get `TypeError: PhpBench\Util\MemoryUnit::resolveSuitableBinaryUnit(): Return value must be of type string, null returned`
=> Fixed TypeError in MemoryUnit.php

phpstan.neon.dist, phpstan/Container.stub, tests/Unit/Expression/NodePrinter/DisplayAsPrinterTest.php, tests/Unit/Expression/NodePrinterTestCase.php, tests/Unit/Expression/ParseletTestCase.php
This will let us know the type of the object returned by container:
```php
\PHPStan\dumpType($this->container()->get(SomeClass:class)) // "mixed" before change and "SomeClass" after the change
```
=> Phpstan stub for Psr\Container

.php-cs-fixer.dist.php
New release https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.47.0
breaks a lot of things. That's why I disabled `fully_qualified_strict_types`.
=> Disabled fully_qualified_strict_types for php-cs-fixer

tests/Example/CommandsTest.php, tests/Integration/ConfiguredReportsTest.php, tests/System/SystemTestCase.php, tests/Unit/Report/Generator/GeneratorTestCase.php, tests/Unit/Report/Renderer/ConsoleRendererTest.php
Forced `--no-ansi` in tests as without this option it breaks tests if they are running from the terminal supporting colors.
=> Forced `--no-ansi` in tests

.php-cs-fixer.dist.php, lib/Console/CharacterReader.php
The call to `readline_callback_handler_install` in `CharacterReader` is causing some junk output (see below) *in all commands* that was breaking the CSV output. Clearing out `TERM` and `COLORTERM` also prevents the issue.
This commit defers the installation of the readline callback handler until log is actually run.
```console
$ COLORTERM="truecolor" TERM="xterm-256color" php -r "readline_callback_handler_install('', function (): void {});" | xxd
00000000: 1b5b 3f32 3030 3468 1b5b 3f32 3030 346c  .[?2004h.[?2004l
00000010: 0d                                       .
$ COLORTERM= TERM= php -r "readline_callback_handler_install('', function (): void {});" | xxd
$ COLORTERM="truecolor" TERM="xterm-256color" php -r "" | xxd
```
Fixes #1090
=> Defer CharacterReader initialization until command execution

CHANGELOG.md, lib/Logger/ConsoleLogger.php, lib/Report/Generator/ExpressionGenerator.php
Not all executors provide the fields used by the default reports which can result in disturbing error messages being logged.
This commit changes the log level to WARNING for evaluation errors and moves the "show messages" log level to WARNING.
Previously:
=> Do not show ERROR log message if field not found

lib/Executor/Method/ErrorHandlingExecutorDecorator.php
3rd exception parameter $throwable can be used to get original exception. 
I think it could be useful when debugging exceptions.
=> If \PhpBench\Executor\Method\ErrorHandlingExecutorDecorator throws unhandled exception now is a bit clearer why

CHANGELOG.md, composer.json
This reverts commit 3a9e8836ed264c0efac6651c0e20bede9ace2ecc.
Defauly Symfony projects already `replace` all teh polyfills, leading to an error that can onoly be solved by removing the `replace` in the consuming project:
```
composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "7.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- __root__ is present at version dev-main and cannot be modified by Composer
- phpbench/phpbench[dev-master, 1.2.x-dev] cannot be installed as that would require removing __root__[dev-main]. They both replace symfony/polyfill-php81 and thus cannot coexist.
- Root composer.json requires phpbench/phpbench dev-master -> satisfiable by …
```
=> Revert "Removed useless polyfills (#1056)"

CHANGELOG.md, docs/quick-start.rst, lib/Config/ConfigManipulator.php, lib/Console/Command/ConfigExtendCommand.php, lib/Console/Command/ConfigInitCommand.php, lib/Extension/CoreExtension.php, lib/Extension/ReportExtension.php, lib/Extension/RunnerExtension.php, lib/Registry/ConfigurableRegistry.php, lib/Registry/Registries.php, phpbench.json, tests/System/ConfigExtendCommandTest.php, tests/System/ConfigInitCommandTest.php, tests/System/SystemTestCase.php, tests/Unit/Config/ConfigManipulatorTest.php, tests/Unit/Registry/ConfigurableRegistryTest.php
- Add a command which creates (or updates) a `phpbench.json` file with a populated `$schema`.
- Adds a command to extend an existing service
=> Config Initialization command and extend Service

composer.json
When `dev-master` was required it was because the latest tag did not work.
=> Use tagged version of prophecy

lib/Console/Command/ConfigExtendCommand.php
When we run `phpbench` without any arguments, the help panel is displayed and we can read 
```
config
config:extend         Generate a new service configuration baesd on a named prototype
```
Typo error on `based`
=> Fix typo error on `config:extend` command help description
