phpbench/phpbench

lib/BenchAggregateIterationResult.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, tests/Functional/ReportGenerator/ConsoleReportGeneratorTest.php
This PR enables a given parameter to be expanded into columns.
=> Explode param

lib/BenchPhp.php, lib/BenchRunner.php, lib/BenchSubjectBuilder.php, lib/Console/Command/BenchRunCommand.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, lib/ReportGenerator/XmlTableReportGenerator.php
Output to an XML file and filter which methods are executed.
=> Added XML report generator and added --filter option

composer.json, lib/Benchmark/CollectionBuilder.php, lib/Benchmark/Runner.php, lib/ReportGenerator/BaseTabularReportGenerator.php, lib/ReportGenerator/ConsoleTableReportGenerator.php, tests/Functional/Console/Command/BaseCommandTestCase.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php
Integrating with the `dantleech/data-tables` library to offer better possiblities of presenting data.
=> Integrating with data-tables

lib/ReportGenerator/ConsoleTableReportGenerator.php, tests/Unit/ReportGenerator/ConsoleTableReportGeneratorTest.php
=> Support non-scalar param values in report

lib/Benchmark/Runner.php, tests/Unit/Benchmark/RunnerTest.php
=> Fixed missing exceptions and added tests

lib/ReportGenerator/BaseTabularReportGenerator.php
=> Fixed revolution aggregation

.travis.yml, composer.json, lib/ReportGenerator/ConsoleTableReportGenerator.php
=> Fix for PHP 5.3

bin/phpbench.php, lib/Configuration.php, lib/Console/Application.php, lib/Console/Command/BaseCommand.php, lib/Console/Command/RunCommand.php, lib/ProgressLogger.php, lib/ProgressLogger/DotsProgressLogger.php, lib/ProgressLogger/NullProgressLogger.php, lib/Result/SuiteResult.php, tests/Functional/Bin/BinTest.php, tests/Functional/Console/Command/RunCommandTest.php, tests/Functional/ReportGenerator/BaseReportGeneratorCase.php, tests/Functional/benchmarks/ArrayKeysCase.php, tests/Functional/benchmarks/IsolatedCase.php, tests/Unit/ConfigurationTest.php, tests/phpbench
Configurable progress reports.
=> Configurable progress

README.md, examples/ArrayKeysBench.php, lib/Benchmark/Parser.php, lib/Benchmark/SubjectBuilder.php, tests/Unit/Benchmark/ParserTest.php
Allow annotations at the class level. Fixes #47
=> Class level annotations

lib/Report/Cellular/Step/AggregateRunStep.php, lib/Report/Cellular/Step/DeviationStep.php, lib/Report/Cellular/Step/FooterStep.php, lib/Report/Generator/BaseTabularReportGenerator.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php, tests/Unit/Report/Cellular/Step/AggregateRunStepTest.php, tests/Unit/Report/Cellular/Step/DeviationStepTest.php, tests/Unit/Report/Cellular/Step/FooterStepTest.php
Allows column selectoion for aggregation. Fixes #68
=> Allow selective columns for aggregation

.travis.yml, CHANGELOG.md, composer.json, lib/PhpBench.php
Test with lowest dependencies, fixes #59
Also added and fixed HHVM build.
=> Lowest deps

CHANGELOG.md, README.md, lib/Benchmark/Runner.php, lib/Report/Cellular/CellularConverter.php, lib/Report/Cellular/Step/AggregateRunStep.php, lib/Report/Generator/ConsoleTableReportGenerator.php, tests/Functional/ReportGenerator/BaseTabularReportGeneratorCase.php, tests/Functional/report.xml, tests/Unit/Report/Cellular/CellularConverterTest.php, tests/Unit/Report/Cellular/Step/AggregateRunStepTest.php
Shows the difference between the min and max of the suffixed column as a percentace, aggregations only. Fixes #66
Also adds the PID to the iteration stats, fixing #49
=> Added variance column

CHANGELOG.md, examples/phpbench, lib/Report/Cellular/Step/AggregateSubjectStep.php, lib/Report/Generator/ConsoleTableReportGenerator.php
=> Remove title for aggregated subject

CHANGELOG.md, README.md, examples/phpbench, lib/Report/Cellular/CellularConverter.php, lib/Report/Cellular/Step/AggregateRunStep.php, lib/Report/Generator/BaseTabularReportGenerator.php, lib/Report/Generator/ConsoleTableReportGenerator.php, tests/Functional/benchmarks/IsolatedParametersBench.php, tests/Unit/Report/Cellular/CellularConverterTest.php, tests/Unit/Report/Cellular/Step/AggregateRunStepTest.php
=> Better formatting

CHANGELOG.md, README.md, composer.json, examples/phpbench, lib/Report/Cellular/Step/SortStep.php, lib/Report/Generator/BaseTabularReportGenerator.php, tests/Unit/Report/Cellular/Step/SortStepTest.php
=> Allow sorting by multiple columns

CHANGELOG.md, README.md, lib/Console/Command/RunCommand.php, lib/PhpBench.php, lib/Report/Generator/BaseTabularReportGenerator.php, lib/Report/Generator/ConsoleSimpleReportGenerator.php, tests/Functional/Console/Command/RunCommandTest.php
- Reenabled "footer" option. Fixes #86
- Show memory in simple_table report. Fixes #87
- Disabled default report
-
=> Various fixes:

lib/Benchmark/template/runner.template, lib/Report/Generator/tabular/console_classes.json, lib/Report/ReportManager.php, tests/Unit/Report/ReportManagerTest.php
Check return type from generator's `getSchema` and throw better exception message.
=> Better report config validation

lib/Report/Generator/tabular/console_iteration.json
Show the stability in the default `console_iteration` report.
=> Show stability, do not show sum

lib/Benchmark/CollectionBuilder.php, tests/Unit/Benchmark/CollectionBuilderTest.php, tests/Unit/Benchmark/findertestnested/Directory/MyBench.php, tests/Unit/Benchmark/findertestnested/MyBench.php
=> Fixed the finder depth

lib/Benchmark/BenchmarkBuilder.php, lib/Benchmark/Teleflector.php, lib/Benchmark/template/teleflector.template, tests/Unit/Benchmark/BenchmarkBuilderTest.php, tests/Unit/Benchmark/TeleflectorTest.php, tests/Unit/Benchmark/teleflector/Class1.php, tests/Unit/Benchmark/teleflector/Class2.php, tests/Unit/Benchmark/teleflector/Class3.php
Fixes #95 
Inherit annotations from parent classes
=> Inherit annotations

docs/report_generators.rst, lib/Extension/CoreExtension.php, lib/Report/Generator/AbstractConsoleTabularGenerator.php, lib/Report/Generator/ConsoleTabularCustomGenerator.php, lib/Report/Generator/ConsoleTabularGenerator.php, lib/Report/Generator/tabular/console_iteration.json, tests/Functional/Report/Generator/ConsoleTabularGeneratorTest.php
=> Support for sorting with the default reports.

docs/report_generators.rst, examples/HashBench.php, examples/phpbench.json, lib/Report/Generator/ConsoleTabularGenerator.php, lib/Report/Generator/tabular/console_iteration.json, tests/Functional/Report/Generator/ConsoleTabularGeneratorTest.php
=> Added group filter to default report

docs/configuration.rst, examples/phpbench.json, lib/Console/Command/RunCommand.php, lib/Extension/CoreExtension.php
=> Renamed progress_logger_name to progress

lib/Report/Generator/TabularGenerator.php, tests/Functional/Report/Generator/TabularGeneratorTest.php
=> Fixed issue with table group filter and multiple groups

lib/Benchmark/Metadata/Factory.php, tests/Unit/Benchmark/Metadata/FactoryTest.php
Validate parameter sets provided from param providers. Fixes #152
=> Param Validation

lib/Benchmark/Metadata/DocParser.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php
=> Ignore common annotations

lib/Benchmark/Executor/MicrotimeExecutor.php, lib/Benchmark/Remote/Launcher.php, lib/Benchmark/Remote/Payload.php, lib/Benchmark/Remote/Reflector.php, lib/Extension/CoreExtension.php, tests/Unit/Benchmark/Remote/LauncherTest.php, tests/Unit/Benchmark/Remote/PayloadTest.php, tests/Unit/Benchmark/Remote/launcher/autoload.php, tests/Unit/Benchmark/Remote/template/foo.template
- Includes support for wrapping and assigning PHP ini values
Closes #169
=> Refactored Launcher

.travis.yml, composer.json
=> Support for PHP7

lib/Benchmark/CollectionBuilder.php, lib/Console/Command/RunCommand.php, lib/DependencyInjection/Container.php, lib/Extension/CoreExtension.php, tests/Functional/Console/Command/RunCommandTest.php, tests/Unit/Extension/CoreExtensionTest.php
=> Allow path argument to override config path

lib/Benchmark/CollectionBuilder.php, lib/Benchmark/Metadata/Factory.php, lib/Benchmark/Runner.php, tests/Unit/Benchmark/Metadata/FactoryTest.php
=> Also validate benchmark before/after methods

lib/Benchmark/Metadata/Driver/AnnotationDriver.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php
This PR fixes an issue where methods in child classes without annotations would not inherit the annotations from parent classes.
=> Fix annotation inheritance

README.md, docs/writing-benchmarks.rst, lib/Benchmark/Metadata/AbstractMetadata.php, lib/Benchmark/Metadata/Annotations/Sleep.php, lib/Benchmark/Metadata/DocParser.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Benchmark/Runner.php, lib/Benchmark/SuiteDocument.php, lib/Console/Command/RunCommand.php, tests/System/RunTest.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Benchmark/RunnerTest.php
Allow a sleep period between iterations.
=> Addition of sleep option and annotation

docs/benchmark-runner.rst, lib/Benchmark/CartesianParameterIterator.php, lib/Benchmark/Executor/MicrotimeExecutor.php, lib/Benchmark/Iteration.php, lib/Benchmark/ParameterSet.php, lib/Benchmark/Runner.php, lib/Progress/Logger/VerboseLogger.php, tests/Unit/Benchmark/CartesianIteratorTest.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php, tests/Unit/Benchmark/IterationTest.php, tests/Unit/Benchmark/RunnerTest.php
Show the paramter set number in the verbose logger.
Fixes #200
=> Show parameter set # in verbose logger

README.md, docs/writing-benchmarks.rst, lib/Benchmark/Executor/MicrotimeExecutor.php, lib/Benchmark/Executor/template/benchmark_static_methods.template, lib/Benchmark/Executor/template/microtime.template, lib/Benchmark/ExecutorInterface.php, lib/Benchmark/Metadata/Annotations/AbstractArrayAnnotation.php, lib/Benchmark/Metadata/Annotations/AbstractMethodsAnnotation.php, lib/Benchmark/Metadata/Annotations/AfterClassMethods.php, lib/Benchmark/Metadata/Annotations/AfterMethods.php, lib/Benchmark/Metadata/Annotations/BeforeClassMethods.php, lib/Benchmark/Metadata/Annotations/Groups.php, lib/Benchmark/Metadata/BenchmarkMetadata.php, lib/Benchmark/Metadata/DocParser.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Benchmark/Metadata/Factory.php, lib/Benchmark/Remote/Payload.php, lib/Benchmark/Remote/ReflectionHierarchy.php, lib/Benchmark/Remote/ReflectionMethod.php, lib/Benchmark/Remote/Reflector.php, lib/Benchmark/Remote/template/reflector.template, lib/Benchmark/Runner.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php, tests/Unit/Benchmark/Executor/microtimetest/ExecutorBench.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Benchmark/Metadata/FactoryTest.php, tests/Unit/Benchmark/Remote/PayloadTest.php, tests/Unit/Benchmark/Remote/ReflectionHierarchyTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Util/TestUtil.php
Execute static methods before and after benchmark classes. Fixes #206
=> Before and After Class

lib/Benchmark/Runner.php, lib/Benchmark/RunnerContext.php, lib/Console/Command/RunCommand.php, tests/Unit/Benchmark/RunnerContextTest.php, tests/Unit/Benchmark/RunnerTest.php
Introduces a runner context class for configuring the runner.
=> Runner context

docs/benchmark-runner.rst, lib/Benchmark/Runner.php, lib/Extension/CoreExtension.php, lib/Progress/Logger/DotsLogger.php, lib/Progress/Logger/TravisLogger.php, tests/Unit/Extension/CoreExtensionTest.php, tests/Unit/Progress/Logger/DotsLoggerTest.php, tests/Unit/Progress/Logger/TravisLoggerTest.php
Experiment with progress loggers that do not break travis output.
=> Travis compat

lib/Benchmark/Remote/Reflector.php, lib/PhpBench.php
=> Fixed non-existing key "bootstrap"

.travis.yml, composer.json, examples/phpbench.json, lib/Console/Application.php, tests/System/ReportTest.php, tests/System/RunTest.php
Allow usage of Symfony 3.0 components.
=> Symfony 3.0 support

lib/Benchmark/Remote/Payload.php
=> Disable timeout on Process

lib/Benchmark/SuiteDocument.php, tests/Unit/Benchmark/SuiteDocumentTest.php, tests/Unit/Benchmark/document/document.xml, tests/Unit/Benchmark/document/empty.xml
=> No crash on division by zero

lib/Progress/Logger/TravisLogger.php, tests/Unit/Progress/Logger/TravisLoggerTest.php
=> Travis logger show iterations

README.md, docs/benchmark-runner.rst, docs/configuration.rst, docs/quick-start.rst, docs/report-renderers.rst, docs/reports.rst, docs/writing-benchmarks.rst, lib/Benchmark/Executor/BaseExecutor.php, lib/Benchmark/ExecutorInterface.php, lib/Benchmark/Iteration.php, lib/Benchmark/IterationCollection.php, lib/Benchmark/Metadata/BenchmarkMetadata.php, lib/Benchmark/Remote/ReflectionHierarchy.php, lib/Registry/Registry.php, lib/Util/TimeUnit.php
=> Fixed typos

lib/Report/Generator/Tabular/aggregate.json, tests/Functional/Report/Generator/TabularGeneratorTest.php
=> Readded diff column

docs/report-renderers.rst, lib/Registry/Config.php, lib/Registry/Registry.php, lib/Report/Generator/AbstractTabularGenerator.php, lib/Report/Generator/CompositeGenerator.php, lib/Report/Renderer/XsltRenderer.php, lib/Report/schema/report.xsd, tests/Functional/Report/Generator/GeneratorTestCase.php, tests/Unit/Benchmark/Executor/DebugExecutorTest.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Registry/ConfigTest.php, tests/Unit/Registry/RegistryTest.php, tests/Unit/Report/Generator/CompositeGeneratorTest.php, tests/Unit/Report/Renderer/AbstractRendererCase.php, tests/Unit/Report/Renderer/ConsoleRendererTest.php, tests/Unit/Report/Renderer/XsltRendererTest.php, tests/Unit/Report/ReportManagerTest.php
Would fix https://github.com/phpbench/phpbench/issues/280
=> Report name token

lib/Benchmark/Runner.php, tests/System/RunTest.php, tests/System/SystemTestCase.php
=> Overidden revolutions recorded in XML doc.

lib/Extension/config/report/renderers.php, lib/Report/Renderer/XsltRenderer.php, tests/Unit/Report/Renderer/XsltRendererTest.php
=> Allow null fname in XSLT report

lib/Report/Renderer/DelimitedRenderer.php
=> Show headers by default in delimited report

lib/Console/Command/Handler/RunnerHandler.php, lib/Console/Command/Handler/TimeUnitHandler.php, lib/Console/Command/ReportCommand.php, lib/Console/Command/RunCommand.php, lib/Extension/CoreExtension.php, tests/System/ReportTest.php
=> Specify time units in report command

lib/Registry/Registry.php
=> Better exception when no generator|extends

README.md, docs/environment.rst, docs/index.rst, docs/reports.rst, lib/Benchmark/Runner.php, lib/Environment/Information.php, lib/Environment/Provider/Git.php, lib/Environment/Provider/Php.php, lib/Environment/Provider/Uname.php, lib/Environment/Provider/UnixSysload.php, lib/Environment/ProviderInterface.php, lib/Environment/Supplier.php, lib/Environment/VcsInformation.php, lib/Extension/CoreExtension.php, lib/Extension/config/report/generators.php, lib/Report/Generator/AbstractTabularGenerator.php, lib/Report/Generator/Tabular/env.json, tests/Unit/Benchmark/RunnerTest.php, tests/Unit/Environment/InformationTest.php, tests/Unit/Environment/Provider/GitTest.php, tests/Unit/Environment/Provider/PhpTest.php, tests/Unit/Environment/Provider/UnameTest.php, tests/Unit/Environment/Provider/UnixSysloadTest.php, tests/Unit/Environment/SupplierTest.php
This PR will add environemental information to the suite XML document.
- All information from `php_uname`
- PHP build information.
- VCS information.
```xml
<phpbench version="0.10.0-dev">
<suite context="" date="2016-01-13T16:04:42+01:00" config-path="" retry-threshold="">
<env>
<unname os="Linux" host="dtlt410" release="4.2.0-1-amd64" version="#1 SMP Debian 4.2.6-1 (2015-11-10)" machine="x86_64"/>
<vcs system="git" branch="env_info" version="b9bd94994170ff45dc58b13c8842e81d5470ea99"/>
<php version="5.6.15-1"/>
<sysload m1="0.46" m5="0.37" m15="0.42"/>
</env>
```
Will partially address #269
=> [WIP] Environmental information

lib/Benchmark/IterationCollection.php, lib/Extension/config/benchmark/executors.php, lib/Progress/Logger/AnsiLogger.php, lib/Progress/Logger/BlinkenLogger.php, lib/Progress/Logger/PhpBenchLogger.php, lib/Progress/Logger/TravisLogger.php, lib/Progress/Logger/VerboseLogger.php, tests/Unit/Progress/Logger/BlinkenLoggerTest.php, tests/Unit/Progress/Logger/TravisLoggerTest.php
- Better code reuse between loggers.
- Better rendering for the blinken logger.
=> Imroved progress loggers.

docs/benchmark-runner.rst, lib/Benchmark/IterationCollection.php, lib/Extension/CoreExtension.php, lib/Extension/config/report/generators.php, lib/Math/Statistics.php, lib/Progress/Logger/HistogramLogger.php, lib/Report/Generator/HistogramGenerator.php, tests/Functional/Report/Generator/HistogramGeneratorTest.php, tests/Unit/Math/StatisticsTest.php, tests/Unit/Progress/Logger/HistogramLoggerTest.php
Shows Z-Score distribution at end of each iteration set cycle.
```
(σ = 0.301679 ) -3σ [                    ▄  ▄█ █     ▄   ▄     ▄               ▄     ] +3σ (mean = 1.574μs)
```
=> Histogram logger

benchmarks/Macro/BaseBenchCase.php, benchmarks/Macro/_workspace/dump.xml, benchmarks/Micro/DependencyInjection/ContainerBench.php, extensions/xdebug/lib/XDebugExtension.php, lib/DependencyInjection/Container.php, lib/DependencyInjection/ExtensionInterface.php, lib/Extension/CoreExtension.php, lib/PhpBench.php, tests/Functional/FunctionalTestCase.php, tests/Unit/DependencyInjection/ContainerTest.php, tests/Unit/Extension/CoreExtensionTest.php
Changes the Container intiialization to make the workflow more sensible.
Fixes #309
=> Container initialization refactoring.

benchmarks/Micro/DependencyInjection/ContainerBench.php, benchmarks/Micro/Math/KdeBench.php, docs/writing-benchmarks.rst, extensions/sqlite/lib/Storage/Driver/Sqlite/ConstraintVisitor.php, extensions/sqlite/lib/Storage/Driver/Sqlite/Loader.php, extensions/sqlite/lib/Storage/Driver/Sqlite/Persister.php, extensions/sqlite/lib/Storage/Driver/Sqlite/sqlite.sql, extensions/sqlite/tests/Functional/Storage/Driver/Sqlite/LoaderTest.php, lib/Benchmark/Metadata/Annotations/OutputTimeUnit.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Benchmark/Metadata/SubjectMetadata.php, lib/Benchmark/RunnerContext.php, lib/Model/Benchmark.php, lib/Model/Subject.php, lib/Progress/Logger/PhpBenchLogger.php, lib/Serializer/XmlDecoder.php, lib/Serializer/XmlEncoder.php, lib/Util/TimeUnit.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Model/BenchmarkTest.php, tests/Unit/Progress/Logger/BlinkenLoggerTest.php, tests/Unit/Progress/Logger/HistogramLoggerTest.php, tests/Unit/Progress/Logger/TravisLoggerTest.php, tests/Unit/Progress/Logger/VerboseLoggerTest.php, tests/Unit/Serializer/XmlTestCase.php, tests/Util/TestUtil.php
- Allow setting of precision as an annoatation
- CLI option will override.
- Precision stored in XML.
Fixes #262
=> Precision annotation

docs/faq.rst, docs/index.rst
=> Documentation: FAQ

lib/Report/Generator/TableGenerator.php, tests/Unit/Report/Generator/TableGeneratorTest.php
=> Fixed "time" column for iter report and added test.

benchmarks/Macro/BaseBenchCase.php, lib/Progress/Logger/BlinkenLogger.php
=> Blinken logger rendering fixes.

lib/Progress/Logger/BlinkenLogger.php
=> Fixed bliken logger spacing issue.

extensions/dbal/lib/Storage/Driver/Dbal/Visitor/SqlVisitor.php, extensions/dbal/tests/Unit/Storage/Driver/Dbal/Visitor/SqlVisitorTest.php, lib/Report/Generator/TableGenerator.php, tests/Unit/Report/Generator/TableGeneratorTest.php
=> Row normalization and sql visitor state reseting.

docs/storage.rst, extensions/dbal/lib/DbalExtension.php, extensions/dbal/lib/Storage/Driver/Dbal/Repository.php, extensions/dbal/lib/Storage/Driver/Dbal/Visitor/TokenValueVisitor.php, extensions/dbal/tests/Functional/Storage/Driver/Dbal/HistoryIteratorTest.php, extensions/dbal/tests/Functional/Storage/Driver/Dbal/LoaderTest.php, extensions/dbal/tests/Functional/Storage/Driver/Dbal/RepositoryTest.php, extensions/dbal/tests/Unit/Storage/Driver/Dbal/Visitor/TokenValueVisitorTest.php, lib/Console/Command/Handler/SuiteCollectionHandler.php, lib/Console/Command/ShowCommand.php, lib/Extension/CoreExtension.php, lib/Storage/Driver/Xml/HistoryIterator.php, lib/Storage/UuidResolver.php, tests/Unit/Storage/UuidResolverTest.php
Globally resolve meta token UUIDs such as "latest", and `latest-1`, `latest-2` etc.
=> UUID resolver

lib/Benchmark/Remote/ReflectionHierarchy.php, lib/Benchmark/Remote/Reflector.php, lib/Benchmark/Runner.php, lib/Report/Generator/TableGenerator.php, lib/Storage/Archiver/XmlArchiver.php, tests/Unit/Benchmark/RunnerTest.php
Fix for #382 
Need to add a test.
=> Fix skipping benchmarks

lib/Extension/CoreExtension.php, tests/System/ReportTest.php
Readdition of the `composite` generator. Fixes #387
=> Readded composite generator

lib/Report/Generator/TableGenerator.php, tests/Unit/Report/Generator/TableGeneratorTest.php
=> Fixed compare field ommision

docs/report-generators.rst, lib/Console/Command/ShowCommand.php, lib/Report/Generator/EnvGenerator.php, lib/Report/Generator/TableGenerator.php, lib/Report/Renderer/ConsoleRenderer.php, lib/Report/Renderer/templates/html.xsl, lib/Report/Renderer/templates/markdown.xsl, lib/Report/schema/report.xsd, tests/Unit/Report/Generator/EnvGeneratorTest.php, tests/Unit/Report/Generator/TableGeneratorTest.php
Allow column labels to be specified.
=> Column labels

extensions/xdebug/lib/Executor/XDebugExecutor.php
Normalize XDebug path, fixes #395
=> Normalize XDebug path, fixes #395

lib/Benchmark/Metadata/Factory.php, tests/Unit/Benchmark/Metadata/FactoryTest.php
=> Show better exception message when beforeMethod is static

lib/Benchmark/Exception/StopOnErrorException.php, lib/Benchmark/Runner.php, lib/Benchmark/RunnerContext.php, lib/Console/Command/Handler/RunnerHandler.php, tests/System/RunTest.php
=> Stop on error

bin/phpbench.php, docs/extensions/custom.rst, docs/index.rst, lib/Extension/CoreExtension.php, lib/PhpBench.php
Allow an additional autoloader to be sepcified via. the `extension_autoloader` configuration option.
=> Allow additional extension autoloader to be configured + custom extension doc.

lib/Benchmark/Metadata/Annotations/BeforeClassMethods.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php
=> Only allow before|afterClass at class level

lib/Benchmark/Remote/Reflector.php, tests/Unit/Benchmark/Remote/ReflectorTest.php, tests/Util/TestUtil.php
=> No exception for empty file

docs/configuration.rst, docs/writing-benchmarks.rst, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Extension/CoreExtension.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php
Allow use of custom pattern for matching benchmark subjects.
=> Allow custom subject pattern

.travis.yml, lib/Report/Generator/TableGenerator.php, tests/Unit/Report/Generator/TableGeneratorTest.php
=> Prevent division by zero

lib/Report/Renderer/XsltRenderer.php
=> Check for XSL extension

lib/Console/Command/DeleteCommand.php, lib/Console/Command/LogCommand.php, lib/Console/Command/ReportCommand.php
=> Fix command docs

lib/Report/Generator/TableGenerator.php, tests/Unit/Report/Generator/TableGeneratorTest.php
=> Do not allow column name customization by index

lib/Benchmark/Executor/template/microtime.template
... to not use variable function call and use a compiled number of revolutions.
=> Optimized microtime template

tests/System/RunTest.php, tests/Unit/Benchmark/Executor/MicrotimeExecutorTest.php
=> Fix: Use more appropriate assertions

extensions/xdebug/tests/Unit/Executor/TraceExecutorTest.php, lib/Benchmark/Executor/template/health_check.template, lib/Benchmark/Remote/Launcher.php, lib/Benchmark/Remote/Payload.php, lib/Environment/Information.php, lib/Environment/Provider/AbstractRemoteProvider.php, lib/Environment/Provider/Opcache.php, lib/Environment/Provider/Php.php, lib/Environment/Provider/template/opcache.template, lib/Extension/CoreExtension.php, tests/Unit/Environment/InformationTest.php, tests/Unit/Environment/Provider/OpcacheTest.php, tests/Unit/Environment/Provider/PhpTest.php
Simply show if the opcache is enabled in the benchmarking environment:
=> Introduced Opcode env provider

composer.json, lib/Benchmark/Remote/Payload.php, lib/PhpBench.php, tests/Unit/Benchmark/Remote/PayloadTest.php
=> Windows paths

lib/Extension/config/report/generators.php
=> Do not use env-specific column (vcs_branch) in default report

lib/Report/Renderer/templates/html.xsl
Add utf-8 to html report.
See #519
=> Add utf-8 charset to html report

extensions/xdebug/lib/Converter/TraceToXmlConverter.php
=> Use text node for trace dom element

CHANGELOG.md, README.md, benchmarks/Micro/HashingBench.php, benchmarks/Micro/Math/KdeBench.php, docs/writing-benchmarks.rst, lib/Benchmark/Remote/template/parameter_set_extractor.template, tests/Unit/Benchmark/Executor/ParameterSetExtractorTest.php, tests/Unit/Benchmark/Executor/benchmarks/ParamProviderBench.php
Allow Traversables (including generators! :tada: ) to be returned from param providers.
=> Param provider generator

composer.json
This PR
💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/compare/v2.11.0...v2.13.1.
=> Enhancement: Update friendsofphp/php-cs-fixer

lib/Benchmark/Metadata/AnnotationReader.php, lib/Console/Command/RunCommand.php, lib/Formatter/Format/TimeUnitFormat.php, lib/Formatter/Format/TruncateFormat.php, lib/Formatter/Formatter.php, lib/Math/Statistics.php, lib/Report/Renderer/XsltRenderer.php, lib/Serializer/XmlEncoder.php, lib/Storage/Driver/Xml/XmlDriver.php, phpstan.neon
=> Enhancement: Raise phpstan level from 4 to 5

lib/Executor/Benchmark/MemoryCentricMicrotimeExecutor.php, lib/Executor/Benchmark/MemoryExecutor.php, lib/Executor/Benchmark/template/memory.template, lib/Extension/CoreExtension.php, lib/Extension/config/benchmark/executors.php, tests/System/RunTest.php
Introduces a new `memory_centric_microtime` executor which does a better job of measuring memory usage.
=> Memory-centric executor

extensions/dbal/lib/Storage/Driver/Dbal/Schema.php
- DB: 'environment'.'value now to be TEXT
=> Fixes #620

tests/Unit/Model/IterationTest.php, tests/Unit/Model/SubjectTest.php, tests/Unit/Model/VariantTest.php
=> fixed some test namespaces

composer.json, extensions/xdebug/lib/Command/ProfileCommand.php, extensions/xdebug/lib/Command/TraceCommand.php, lib/Console/CharacterReader.php, lib/Console/Command/ArchiveCommand.php, lib/Console/Command/DeleteCommand.php, lib/Console/Command/LogCommand.php, lib/Console/Command/ReportCommand.php, lib/Console/Command/SelfUpdateCommand.php, lib/Console/Command/ShowCommand.php, lib/Formatter/Format/BalanceFormat.php, lib/Formatter/Format/NumberFormat.php, lib/Formatter/Formatter.php, lib/Model/Benchmark.php, lib/Report/Renderer/ConsoleRenderer.php, lib/Report/Renderer/DelimitedRenderer.php, lib/Report/Renderer/XsltRenderer.php, lib/Serializer/XmlDecoder.php, lib/Storage/Driver/Xml/XmlDriver.php, phpstan.neon
Fixes #638 
Updated PHPStan to allow the installation of 5.1 in dev mode and "fixed" some new issues due to that.
=> Fix for Symfony Console 5.1

README.md
A comma would make more sense in this sentence. 
Forget it if that was intended.
=> Punctuation: replace dot with comma

docs/development.rst, docs/development/debugging.rst, docs/development/extensions.rst, docs/index.rst, lib/Benchmark/Remote/Payload.php, lib/Benchmark/Remote/PayloadFactory.php, lib/Executor/Benchmark/TemplateExecutor.php, lib/Extension/CoreExtension.php, phpunit.xml.dist, tests/System/RunTest.php, tests/Unit/Benchmark/Remote/PayloadTest.php
Added option to place temporary script files in a specific location, and to keep them rather than remove them.
=> Remote script remove

CHANGELOG.md, composer.json, docs/development/extensions.rst, extensions/xdebug/lib/XDebugExtension.php, lib/Extension/CoreExtension.php
Use OptionsResolver rather than returning an array of default values.
=> Use OptionsResolver in extensions

CHANGELOG.md, composer.json, extensions/xdebug/lib/Executor/ProfileExecutor.php, lib/Benchmark/BenchmarkFinder.php, lib/Benchmark/Runner.php, lib/Benchmark/RunnerConfig.php, lib/Console/Command/Handler/RunnerHandler.php, lib/Executor/Benchmark/TestExecutor.php, lib/Extension/CoreExtension.php, lib/Model/Suite.php, lib/Registry/RegistrableInterface.php, tests/Unit/Benchmark/BenchmarkFinderTest.php, tests/Unit/Benchmark/RunnerConfigTest.php, tests/Unit/Benchmark/RunnerTest.php
- Extracts "finder" from the "Runner"
- Use generator in "finder" (it will no longer eagerly load all metadata for all subjects)
=> Runner refactor

docs/reports.rst
This was reported by DOCtor-RST
=> Fix: Indention

.github/workflows/documentation.yml, .readthedocs.yml, docs/.doctor-rst.yaml, docs/conf.py, docs/requirements.txt
You can see the first run after merging this PR, this is security feature of GithubActions.
You can check how it looks like in https://github.com/OskarStark/phpbench/pull/1
I will take care of the commented rules in `.doctor-rst.yaml` after merging of this PR 👍
=> Enhancement: Add Sphinx build and DOCtor-RST linting via GithubActions

.travis.yml
=> Fix: Remove stage

composer.json, phpbench.json.dist
- Support direct reference to services
- Require "tokenizer" extension
=> Ensure correct extensions are loaded for examples profile.

CHANGELOG.md, lib/Benchmark/RunnerConfig.php, lib/Model/Tag.php, lib/Storage/Exception/InvalidTagException.php, lib/Storage/Exception/TagNotFoundException.php, lib/Storage/HistoryEntry.php, lib/Storage/UuidResolver/TagResolver.php, tests/System/LogTest.php, tests/Unit/Model/TagTest.php, tests/Unit/Storage/UuidResolver/TagResolverTest.php
=> Tag parsing

.github/workflows/release-phar.yml, composer.json
Working example from fork - https://github.com/Jeckerson/phpbench-1/runs/1468396755?check_suite_focus=true
=> Phar GitHub actions

lib/Assertion/ExpressionParser.php, lib/Console/Application.php, lib/Extension/CoreExtension.php, tests/Unit/Assertion/ExpressionParserTest.php
=> Configure IO in DI container

CHANGELOG.md, lib/Benchmark/BenchmarkFinder.php, lib/Console/Command/Handler/RunnerHandler.php, lib/Extension/CoreExtension.php, tests/System/RunTest.php, tests/Unit/Benchmark/BenchmarkFinderTest.php, tests/Unit/Extension/CoreExtensionTest.php
- Permit multiple paths to be provided in config
- Add type restrictions to config values
=> Multiple paths

lib/Assertion/ExpressionEvaluator.php, lib/Assertion/VariantAssertionResults.php, phpunit.xml.dist, tests/Unit/Assertion/Ast/ComparisonTest.php, tests/Unit/Model/SummaryTest.php
Following #743 keep the internal tolerance result as it's useful for feedback
=> Keep tolerance assertion result

lib/Assertion/ExpressionEvaluator.php, tests/Unit/Assertion/Ast/ComparisonTest.php, tests/Unit/Assertion/ExpressionEvaluatorTest.php
=> Tolerance applies either side of targets

CHANGELOG.md, lib/Expression/Ast/DisplayAsNode.php, lib/Expression/Ast/UnitNode.php, lib/Expression/Ast/ValueWithUnitNode.php, lib/Expression/ColorMap/TrueColorMap.php, lib/Expression/NodeEvaluator/ValueWithUnitEvaluator.php, lib/Expression/NodePrinter/DisplayAsPrinter.php, lib/Expression/NodePrinter/UnitPrinter.php, lib/Expression/NodePrinter/ValueWithUnitPrinter.php, lib/Expression/Parselet/DisplayAsParselet.php, lib/Expression/Parselet/ValueWithUnitParselet.php, lib/Extension/ExpressionExtension.php, tests/Unit/Expression/Parselet/DisplayAsParseletTest.php, tests/Unit/Expression/Parselet/ValueWithUnitParseletTest.php
- Allow the display unit to be _evaluated_ (for dynamically determining the unit based on the subject's preference)
- Make the `unit` a node - allowing it to be pretty printed.
=> Dedicated Unit Value node

CHANGELOG.md, examples/Extension/AcmeExtension.php, lib/Console/Command/Handler/RunnerHandler.php, lib/Extension/CoreExtension.php, tests/System/RunTest.php
Send all progress output to STDERR, allowing (report) output to be piped to other tools or files.
=> Progress to stderr

CHANGELOG.md, docs/annotributes.rst, examples/Annotations/AnnotatedBench.php, examples/Attributes/AttriutedBench.php, lib/Attributes/RetryThreshold.php, lib/Benchmark/Metadata/AnnotationReader.php, lib/Benchmark/Metadata/Annotations/RetryThreshold.php, lib/Benchmark/Metadata/Driver/AnnotationDriver.php, lib/Benchmark/Metadata/Driver/AttributeDriver.php, lib/Benchmark/Metadata/Driver/ConfigDriver.php, lib/Benchmark/Metadata/SubjectMetadata.php, lib/Benchmark/Runner.php, lib/Extension/CoreExtension.php, tests/Unit/Benchmark/Metadata/Driver/AnnotationDriverTest.php, tests/Unit/Benchmark/Metadata/Driver/AttributeDriverTest.php, tests/Unit/Benchmark/Metadata/Driver/ConfigDriverTest.php
Support RTT attribute
Added documentation
=> Support retry threhsold annotation and config

bin/phpbench.php, lib/Console/Command/ConfigReferenceCommand.php, lib/Console/Command/Handler/DumpHandler.php, lib/Console/Command/LogCommand.php, lib/Extension/DevelopmentExtension.php, lib/Extension/StorageExtension.php, lib/PhpBench.php, tests/System/LogTest.php, tests/System/ReportTest.php, tests/System/RunTest.php, tests/System/ShowTest.php, tests/System/SystemTestCase.php, tests/System/benchmarks/set1/BenchmarkBench.php, tests/System/benchmarks/set1/IsolatedBench.php, tests/System/benchmarks/set1/IsolatedParametersBench.php, tests/System/benchmarks/set1/IsolatedRevsBench.php, tests/System/benchmarks/set1/ParameterProviderCallableBench.php, tests/System/env/config_valid/phpbench.json, tests/Unit/Console/Command/LogCommandTest.php, tests/Util/Approval.php
Various improvements made while trying to improve the E2E test speed
=> Command improvements

examples/Benchmark/NothingBench.php, tests/Example/CommandsTest.php
Incease performance of documentation command tests by running them in-process
=> Use in process commands

CHANGELOG.md, docs/configuration.rst, examples/Benchmark/Macro/BaseBenchCase.php, extensions/xdebug/lib/Command/Handler/OutputDirHandler.php, extensions/xdebug/lib/Executor/ProfileExecutor.php, extensions/xdebug/lib/XDebugExtension.php, extensions/xdebug/tests/System/ProfileCommandTest.php, lib/Benchmark/BenchmarkFinder.php, lib/Console/Application.php, lib/Environment/Provider/Git.php, lib/Extension/CoreExtension.php, lib/Extension/RunnerExtension.php, lib/Extension/StorageExtension.php, lib/PhpBench.php, tests/Unit/Benchmark/BenchmarkFinderTest.php, tests/Unit/Environment/Provider/GitTest.php
Add a `--working-dir` option and remove instances of `getcwd`
=> Working dir

lib/Serializer/XmlEncoder.php, tests/Unit/Serializer/XmlTestCase.php
closes https://github.com/phpbench/phpbench/issues/818
requires https://github.com/phpbench/dom/pull/3
=> added failing XmlEncoder testcase regarding ampersand

composer.json, lib/PhpBench.php
Use composer2 InstalledVersions or show "unknown version"
Fixes #821
=> Remove deprecated package versions

CHANGELOG.md, lib/Serializer/XmlDecoder.php, lib/Serializer/XmlEncoder.php, phpstan-baseline.neon, tests/Unit/Serializer/XmlDecoderTest.php, tests/Unit/Serializer/XmlEncoderTest.php, tests/Unit/Serializer/XmlTestCase.php, tests/Unit/Serializer/examples/date1.example
=> Serialize objects

CHANGELOG.md, lib/Expression/Ast/PhpValueFactory.php, lib/Expression/Ast/UnrepresentableValueNode.php, lib/Expression/NodePrinter/UnrepresentableValuePrinter.php, lib/Extension/ExpressionExtension.php, tests/Unit/Expression/Ast/PhpValueFactoryTest.php, tests/Unit/Expression/NodePrinter/UnrepresentableValuePrinterTest.php
=> Fix exception on unrepresentable values

.php_cs.dist, lib/Model/Tag.php
- Fixed a typo in the InvalidTagException message on Model Tag
- Deleted duplicated key `ordered_imports` on .php_cs.dist
=> A couple of small fixes

lib/Extension/ReportExtension.php, lib/Template/Expression/Printer/SkipTemplateNode.php, lib/Template/Expression/Printer/TemplateNodePrinter.php, lib/Template/Expression/Printer/TemplatePrinter.php, templates/html/Report.phtml, templates/html/Table.phtml, templates/html/node/StringNode.phtml, tests/Unit/Report/Renderer/template/default, tests/Unit/Report/Renderer/template/with-title
- Add HTML escaping,
- Add proper solution to avoid template render recursion (fixing issue with nodes being decorated twice)
=> Fix escaping

lib/Extension/ReportExtension.php, lib/Extension/config/report/generators.php, lib/Report/Console/Renderer/BarChartRenderer.php, lib/Report/Model/BarChart.php, templates/html/BarChart.phtml, tests/Unit/Report/Renderer/template/default, tests/Unit/Report/Renderer/template/with-title
Support Y-Axis formattin (i.e. use configured y axes expression to evaluate axis labels instead of using the raw value)
=> Y axis formatting

docs/report-components/options/_section.rst, docs/report-generators/options/_component.rst, lib/Report/Generator/ComponentGenerator.php, lib/Report/Model/TableRow.php, tests/Unit/Report/Generator/ComponentGeneratorTest.php
Support `filter` expression in component generator / section component.
=> Filter data frame

CHANGELOG.md, examples/Command/report-component-barchart-aggregate, examples/Command/report-component-table-aggregate, lib/Expression/Lexer.php, lib/Expression/Parselet/StringParselet.php, tests/Unit/Expression/Lexer/string_1.test, tests/Unit/Expression/Lexer/string_2.test
Allow single quoteed strings in expressions
=> Single quote

CHANGELOG.md, docs/configuration-prelude.rst, docs/configuration.rst, lib/Config/ConfigLinter.php, lib/Config/ConfigLoader.php, lib/Config/ConfigProcessor.php, lib/Config/Exception/ConfigFileNotFound.php, lib/Config/Exception/LintError.php, lib/Config/Linter/SeldLinter.php, lib/Config/Processor/CallbackProcessor.php, lib/Config/Processor/IncludeGlobProcessor.php, lib/Config/Processor/IncludeProcessor.php, lib/PhpBench.php, phpbench.schema.json, tests/Unit/Config/ConfigLoaderTest.php, tests/Unit/Config/Linter/SeldLinterTest.php, tests/Unit/Config/Processor/IncludeGlobProcessorTest.php, tests/Unit/Config/Processor/IncludeProcessorTest.php
Allows configurations to be included by adding configuration pre processors.
=> Config include

lib/Expression/NodeEvaluator/ArithmeticOperatorEvaluator.php, lib/Expression/Parselet/ArrayAccessParselet.php, lib/Expression/Precedence.php, tests/Unit/Expression/Parselet/ArithmeticOperatorParseletTest.php
=> Access precedence

docs/configuration.rst, lib/Extension/RunnerExtension.php, lib/Remote/ProcessFactory.php, phpbench.schema.json, tests/Unit/Remote/ProcessFactoryTest.php
=> Add support for passing env vars to PHP

CHANGELOG.md, lib/Remote/Payload.php, lib/Storage/UuidResolver/TagResolver.php
Fix the `setPhpPath` behavior, remove another 8.1 deprecation cc @Crell
=> Further 81 fixes

CHANGELOG.md, lib/Report/Model/BarChart.php, tests/Unit/Report/Model/BarChartTest.php
=> Do not sort the XAxes

lib/Extension/RunnerExtension.php, tests/System/RunTest.php, tests/System/benchmarks/set7/nested1/Nothing2Bench.php, tests/System/benchmarks/set7/nested2/Nothing3Bench.php, tests/System/env/config_set7/phpbench.json
=> Added simple check for glob paths in config.path value

CHANGELOG.md, docs/configuration.rst, lib/Expression/NodePrinter/DisplayAsPrinter.php, lib/Extension/ExpressionExtension.php, lib/Util/NumberFormat.php, phpbench.json, phpbench.schema.json, tests/Unit/Util/NumberFormatTest.php
=> Option to strip trailing zeros

lib/Reflection/template/parameter_set_extractor.template, tests/Unit/Executor/ParameterSetExtractorTest.php, tests/Unit/Executor/benchmarks/ParamProviderBench.php
Fix issue fixed in PR #1001 in a slightly different way and adds a test
=> GH-1001: Fix bad exception call

CHANGELOG.md, lib/Util/NumberFormat.php, tests/Unit/Util/NumberFormatTest.php
=> Fix formatting of number with zero decimal precision

composer.json, lib/Benchmark/Metadata/AnnotationReader.php
It should allow other packages to add support for `doctrine/lexer` 3
=> Add support for annotations 2

bin/build-phar.sh, docs/installing.rst
The previous GPG key has expired, but unfortunately I have lost the private key.
I have created a new key fixes #1016 cc @bart-jaskulski
=> New GPG Key

composer.json
Symfony released first beta of symfony 7, so we should support it as well
=> Add support for symfony 7

composer.json, extensions/xdebug/lib/Command/Handler/OutputDirHandler.php, extensions/xdebug/lib/Executor/ProfileExecutor.php, lib/Benchmark/BenchmarkFinder.php, lib/Config/Processor/IncludeGlobProcessor.php, lib/Config/Processor/IncludeProcessor.php, lib/Extension/RunnerExtension.php, lib/Extension/StorageExtension.php, lib/Path/Path.php, lib/PhpBench.php, lib/Report/Renderer/HtmlRenderer.php, lib/Util/PathNormalizer.php, tests/Util/Workspace.php
They can't be installed on php ^8.1
=> Dropped support of old symfony packages

lib/Environment/Provider/Git.php
Fixed code style (php-cs-fixer introduced a new rule in one of the patch releases).
=> Fixed code style

.github/workflows/ci.yaml, lib/Console/CharacterReader.php, lib/Storage/HistoryEntry.php
Add experimental artifact collector to CI build
=> Introudce historian to CI

.gitattributes, .readthedocs.yml
=> Do not ignore schema
